### DISCUSSION TITLE
compare lockfile changes

### DISCUSSION THREAD

**Discussion by bvanjoi** [pnpm/pnpm#16105] [Ideas]
**Describe the user story**

A single pnpm-lockfile stores all the dependent versions of that repository, but in large projects, version changes often lead to git conflicts that are difficult to resolve. In order to make code review easier, we tried to find a way to help users quickly understand how versions of certain projects are changing.

**Describe the solution you'd like**

We know that although the version information is stored in a graph structure in pnpm-lockfile, the dependency versions of the project are actually in a tree structure, e.g.

```yaml
# lockfile
importers:
    packages/a:
         depdencies:
            lodash: 1.0.0
    packages/b:
         depdencies:
            lodash: 1.0.0

packages:
   /lodash/1.0.0
```

can be split into two lockfiles:

```yaml
# packages/a/lockfile
depdencies:
     lodash: 1.0.0

packages: 
    /lodash/1.0.0
```

```yaml
# packages/b/lockfile
dependencies:
    lodash: 1.0.0

packages: 
    /lodash/1.0.0
```

With this feature, for example, when a version change occurs on branch A, such as changing the lodash version to 1.0.1, then at some point, e.g. on ci, a warning can be given about the version of `packages/b/lodash` is different from the version in the lockfile of the master branch, thus preventing unintended changes.

--

I can implement this feature, but in the meantime I'm looking for more suggestions.

- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))
