### DISCUSSION TITLE
pnpm folder structure results in package loading wrong peerDependency

### DISCUSSION THREAD

**Discussion by rdsedmundo** [pnpm/pnpm#3437] [Q&A]
Relevant [issue](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/308#issuecomment-837376463) for context.

I have this monorepo setup:

**\<workspaceRoot>/package.json**
```
  dependencies:
    webpack: 5 
```

**\<workspaceRoot>/packages/react-app**
```
   dependencies:
     storybook: 6.2.9
       webpack: 4 (transitive dependency of storybook)
       pmmmwh/react-refresh-webpack-plugin (transitive dependency of storybook)
           webpack: >=4 (peer dependency of react-refresh)
```

`react-refresh-webpack-plugin` code uses Node native module algorithm, i.e `require('webpack')`, and because everything is hoisted to the virtual store directory, it's choosing the workspaceRoot's webpack version (5) instead of the (4), even though storybook itself executed the plugin with webpack (4). This doesn't happen with Yarn/npm because the folder structure is preserved, i.e the Node algorithm first sees webpack (4) coming from Storybook traversing the tree.

Is this an issue or expected behavior of pnpm? Is there any better solution other than forcing the resolution with the hook as I did in the comment I linked above?
