### DISCUSSION TITLE
Caching node_modules

### DISCUSSION THREAD

**Discussion by zhendalf** [pnpm/pnpm#3636] [Q&A]
When caching dependencies in CI, I have added `**/node_modules` in path:
```yaml
- uses: actions/cache@v2
  with:
    path: |
      ~/.pnpm-store
      **/node_modules
    key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
```

This means that during install step, pnpm doesn't need to create links or run post install build scripts, which makes install step immediate.

I wonder why is this not the default recommended caching template. Is there a downside to caching node_modules?
