### DISCUSSION TITLE
Best way to cache node-gyp output in Gitlab CICD

### DISCUSSION THREAD

**Discussion by reuzel** [pnpm/pnpm#3657] [Q&A]
Hi,

In my node project I have a dependency on a library that builds a binary during install via node-gyp. That takes quite a while, and I would like to prevent this from repeating between builds by caching the output and reuse the constructed binaries. However, I fail to understand what the best configuration is. Which paths and settings must I apply to cache both the node dependencies as well as the related binaries?

Currently, I use something like this:
```
release:
    stage: release
    image: node:15.13.0-alpine3.12

    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - .pnpm-store/

    before_script:
        - apk add jq python3 make g++ linux-headers
        - npm i -g npm
        - npm i -g pnpm
        - pnpm config set store-dir .pnpm-store
        - pnpm config set side-effects-cache true
    script:
        - pnpm install
        - pnpm -r prepare
...
```

I'm not sure if the cache-side-effects is necessary. And the .pnpm-store doesn't seem to contain the binaries? What would be the correct settings here?

Regards,
Joost
