### DISCUSSION TITLE
Cannot run workflow using pnpm

### DISCUSSION THREAD

**Discussion by RobyCigar** [pnpm/pnpm#3953] [Q&A]
Hi i just try to use pnpm for my github workflow 

When the action run, it failed and generate this error.

It says only support for package-lock.json and yarn.lock but not for pnpm-lock.yaml how can I fix this?  
```
1s
1s
Run actions/setup-node@v2
  with:
    node-version: 14.x
    cache: npm
    always-auth: false
    check-latest: false
    token: ***
Found in cache @ /opt/hostedtoolcache/node/14.18.1/x64
/opt/hostedtoolcache/node/14.18.1/x64/bin/npm config get cache
/home/runner/.npm
Error: Dependencies lock file is not found in /home/runner/work/amikom-career-api/amikom-career-api. Supported file patterns: package-lock.json,yarn.lock
```

here's my workflow script
```
# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run build --if-present
      - run: pnpm test

```
