### DISCUSSION TITLE
 ERR_PNPM_UNEXPECTED_STORE  Unexpected store location

### DISCUSSION THREAD

**Discussion by cangSDARM** [pnpm/pnpm#4125] [Q&A]
I want run a command for ci. But pnpm always prompts me that the dependency installation fails

Here is my `.gitlab-ci.yml` file.
```yml
check:
  image: csabasulyok/pnpm:14-alpine
  stage: check
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: always
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
      when: always
  script:
    - echo "check dependencies..."
    - set +e
    # I tried: 
    # pnpm config set store-dir /pnpm-store/
    # pnpm install
    - pnpm add --global --no-optional --prefer-offline danger@10.6.0 lodash.find lodash.includes
    - set -e
    - echo "run ci command..."
    - danger ci --failOnErrors -v
```

I tried those commands before `pnpm add` command: 
- pnpm config set store-dir /pnpm-store/
- pnpm install
- pnpm install --force # As far as I knew, no force command now. So this failed with Unknown option: 'force'

But none of them took effect
Still pripmt following error:
![image](https://user-images.githubusercontent.com/20441896/145966450-b8134ea6-194c-42b0-ae42-a919daf88c47.png)
![image](https://user-images.githubusercontent.com/20441896/145968975-7af31267-22d7-401a-a759-bf6dced998cc.png)

Repo structure
![image](https://user-images.githubusercontent.com/20441896/145969059-3b2357bf-a478-498f-a89b-2e49355e3253.png)

Caused me to be unable to use the danger script

[used docker image](https://hub.docker.com/layers/csabasulyok/pnpm/14-alpine/images/sha256-4b89fc4643bab8eee5f85749265acb0c77b804ff3cef71048d938c066d1376bc?context=explore)
pnpm version: v6

How can I fix it?
