### DISCUSSION TITLE
Should `pnpm-lock.yaml` do not maintains workspaces' versions like `lerna`?

### DISCUSSION THREAD

**Discussion by imcuttle** [pnpm/pnpm#4241] [Q&A] [answered]
In my screen, the project struct as follows
```
root/
  packages/
     a/
     b/
```

**a/package.json**
```json5
{
   "name: "a",
   "version": "1.0.0",
   "dependencies": {
      "b": "^1.0.0"
   }
}
```

**b/package.json**
```json5
{
   "name: "b",
   "version": "1.0.0"
}
```

After I released `1.0.1` version for each package, the `pnpm-lock.yaml` is not updated that cause CI failed.

Let's see `lerna` how to resolve it.

#### Use `lerna publish`

After `lerna bootstrap`, the `package-lock.json` would be generated, and `a/package-lock.json` **without** `b` workspace package meta data.

**`a/package-lock.json`**
```json
{
  "name": "a",
  "version": "1.0.1",
  "dependencies": {}
}
```

So `lerna publish` does not need to handle `b.version` in `lockfile`

```
root/
  packages/
     a/
        package-lock.json
     b/
        package-lock.json
  package-lock.json
```

So, should `pnpm-lock.yaml` maintains workspaces' versions?

```yaml
packages/a:
    specifiers:
      b: ^1.0.1  # should omit this line or not?
    dependencies:
      b: link:../a
```
