### DISCUSSION TITLE
Lockfile assembly, to avoid these PR conflicts

### DISCUSSION THREAD

**Discussion by wbern** [pnpm/pnpm#4324] [Ideas]
Starting a discussion here based on #4322.

My organisation (13 teams, around 110+ monorepo modules and 160+ modules in another repo), are asking us to prioritize this, so I hope we can resolve this. I will direct them to this thread as well, but hope the rush community can pitch in as well.

**Comment by zkochan** [comment]
I understand that it is a big issue. I was thinking about it a lot and I think the only reliable solution would be to not commit the lockfile and to use some storage to upload/fetch it.

We can use the specs from package.json files to create a key. And with that key we can read the lockfile from a cache. But I am not sure how would we then update the lockfile? And if we update it, will it update for all environments? Seems nondeterministic.

Maybe there are other solutions to get rid of the lockfile. But I don't think it is possible to change the format of the lockfile in such a way that conflicts will forever be eliminated.

cc @pnpm/collaborators

**Comment by shellscape** [comment]
We see this occasionally in Rollup and with private repos that resemble the size the OP is speaking of. Whenever we get a conflict we just run `pnpm install` at the root and it's taken care of. I don't understand the use case where that's not sufficient. Sure, it can be a momentary inconvenience, but it's not that big a deal since pnpm is so fast, and it only happens on branches that fall significantly behind master.

**Reply by gluxon** [reply]
> Whenever we get a conflict we just run pnpm install at the root and it's taken care of. I don't understand the use case where that's not sufficient.

I think you're right. In most cases this is sufficient.

From the developer experience perspective though, it's simply frustrating when someone gets the merge conflict prompt and has to wait an additional 30 minutes for a CI pipeline they otherwise wouldn't have to wait for.

We're using a lot of caches on CI too, so these builds end up being slower because the merge conflicts force you to rebase on the tip of develop instead of the last cached commit.

> Sure, it can be a momentary inconvenience, but it's not that big a deal since pnpm is so fast, and it only happens on branches that fall significantly behind master.

pnpm is indeed fast, but we just have other parts of CI that aren't. 😞

Perhaps we're doing some silly non-optimal things, but this does happen to us on branches that fall a couple hours behind if they touch the lock file.

**Comment by gluxon** [comment]
How often does this happen due to dependencies that are expected to be at a consistent version across all packages in a monorepo?

**Edit 2022-03-26: The idea below has been formalized more thoroughly at https://github.com/pnpm/pnpm/discussions/4483**

## Elaborating on my team specifically

We're a little over 700 packages in the monorepo.

On my team, I'd estimate about 20% of pull requests hit `pnpm-lock.yaml` merge conflicts due to this. I'd like to elaborate a bit more about our setup, because I suspect it's actually quite common.

The large frontend monorepo my team works on supports a backend product split into several microservices each exposing their own TypeScript API. Whenever these backend services release a new version, the pull request updating to the new version ripples through and forces a rebase on every PR making a dependency change line-adjacent to it. We're using GitHub Enterprise, so custom merge drivers aren't available.

Here's where we're doing something that may be unique. The `package.json` files themselves don't see a merge conflict since we're abusing `pnpm.overrides` to set the version across all packages in the monorepo. We know `pnpm.overrides` wasn't really meant for this purpose.

Here's a shortened example of our lockfile.

```yaml
overrides:
  '@backend/service-a': 1.0.0
  '@backend/service-b': 1.0.0

projects:

  packages/foo:
    specifiers:
      '@backend/service-a': *
      '@backend/service-b': *
      react: ^17.0.0
    dependencies:
      '@backend/service-a': 1.0.0
      '@backend/service-b': 1.0.0
      react: 17.0.1
```

Backend developers are constantly adding new functionality, and frontend developers are updating their dependency declarations for the new API definitions. You can imagine the following changes merge conflicting with at least one other change in the list:

- Update `@backend/service-a` to `1.0.1`.
- Update `@backend/service-b` to `1.0.1`.
- Add a new `@backend/service-c` to `foo`.
- Remove `@backend/service-a` from `foo`.
- Add a new project `bar` depending on `@backend/service-a` or `@backend/service-b`
- Update `react` to `17.0.2`.

## My Proposal

Perhaps consistent dependencies across a monorepo could be a first-class pnpm feature.

This would be a huge effort, but it would eliminate every merge conflict scenario listed above. I would only consider this if we think many pnpm projects would benefit from this, not just the one I work on.

Here's what it would look like:

The root `package.json` would specify the consistent versions.
   
```json
{
  "name": "some-monorepo",
  "pnpm": {
    "workspaceConsistent": {
      "@backend/service-a": "1.0.0",
 
      "@backend/service-b": "1.0.0",
 
      "react": "17.0.1"
    }
  }
}
```

Projects within the monorepo would use a new protocol.

```json
{
  "name": "foo",
  "dependencies": {
    "@backend/service-a": "workspace-consistent",
    "@backend/service-b": "workspace-consistent",
    "react": "workspace-consistent"
  }
}
```

The `pnpm-lock.yaml` file would look like:

```yaml
# Spaces after each line are intentional to help git auto merge version changes.
'workspace-consistent':
  '@backend/service-a': 1.0.0

  '@backend/service-b': 1.0.0
  
  react: 17.0.1

projects:

  packages/foo:
    specifiers:
      '@backend/service-a': 'workspace-consistent'
      '@backend/service-b': 'workspace-consistent'
      react: 'workspace-consistent'
    dependencies:
      '@backend/service-a': 'workspace-consistent'
      '@backend/service-b': 'workspace-consistent'
      react: 'workspace-consistent'
```

The caveats are:

- The consistent versions in this proposal are exact versions. I'm not sure how necessary supporting standard version ranges would be, and imagine that to be significantly more difficult to implement.
- This would likely require a new lockfile version bump.
- Monorepos would have to upgrade and configure their consistent versions to reduce lockfile merge conflicts.
- Probably other implementation or maintenance difficulty I'm not realizing.

Here's why I think every frontend project would benefit from this, not just my team.

- I've listed `react` as an example here because I think most frontend monorepos should be declaring it at a consistent version. [Multiple copies of React in a frontend bundle can cause hooks to break](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react). There are edge cases where you might have an isolated runtime plugin on a different version of React, but I'd expect that to be rare.
- You generally want the same `@types` definitions for a package. I've seen a lot of TypeScript assignabilty issues that stemmed from packages using different versions of the same `@types` package.
- The `pnpm.overrides` feature (and yarn's `resolutions`) apply too broadly for this use case. Those overrides apply to the entire dependency graph. I'm not aware of a way to make it apply only the dependency declarations in the monorepo. For example, if you accidentally install a new dependency requiring `react@18`, you won't know if `pnpm.overrides.react` is set to `^17.0.0`.

I'd happily volunteer my weekends to work on this if others would find it valuable. I really adore pnpm. ❤️

## Questions

- Would this be helpful to anyone else?
- Are there glaring implementation difficulties?
