### DISCUSSION TITLE
github action build docker image cannot restore pnpm store cache

### DISCUSSION THREAD

**Discussion by michael-land** [pnpm/pnpm#5199] [Q&A]
I'm trying to automate my microservices workflow. Everything is working except the pnpm install cache, (The cache is working fine on my local device, not work on CI environment)

Any help is appreciate.

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/33362998/184248501-de090c45-b0eb-4dc5-97f5-16541658296f.png">

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/33362998/184248673-34d9b2ba-4b20-4a24-a774-9a225aefc00f.png">

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/33362998/184248614-b3a315ad-7d6f-41c7-a36c-27c060af6b0f.png">

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/33362998/184249352-23b325df-8752-4b69-93e6-11407ffed738.png">

Github Workflow

```yaml
jobs:

  build-and-push-image:

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.app }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.app }}-

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: SCOPE=${{ matrix.app }}
          tags: ${{ steps.login-ecr.outputs.registry }}/jtechdigital:${{ matrix.app }}_${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
```

Dockerfile 
```Dockerfile+
FROM base AS builder
COPY . .

ENV CI=true
ARG SCOPE
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store \
    pnpm fetch --frozen-lockfile && \
    pnpm install && \
    pnpm --filter "${SCOPE}..." build --if-present && \
    # deploy package from workspace and skip devDependencies installation
    pnpm --filter "${SCOPE}" deploy --prod dist/program

FROM base
COPY --from=builder /app/dist/program .
CMD pnpm start
```
