### DISCUSSION TITLE
How to properly synchronize node_modules between docker containers and host for a usage in development

### DISCUSSION THREAD

**Discussion by JUNNNI** [pnpm/pnpm#5636] [Q&A]
## Goals

- Create a Package-Based Monorepo with pnpm and its [workspace feature](https://pnpm.io/workspaces).
- Scaffold an entire development project than contain many services with just one `docker-compose up` command.
- Dependencies should be created on the docker instances and synchronized with the host (our local machine)
   - Synchonizing the `node_modules` folders with the host is essentially made for a debugging purpose and would allow IDEs to inspect the dependencies.
    - Dependencies are installed and maintained with docker to avoid cross platforms issues.

_**Note:** this is for a local development purpose only_

Based on those, imagine the following project structure:
```
├── apps
│   ├── api (ExpressJS application)
│       ├── package.json
│       ├── node_modules
│   ├── client (React application)
│       ├── package.json
│       ├── node_modules
├── libs
│   └── common (Typescript compiled folder shared with api and client as a workspace dependencie)
│       ├── package.json
│       ├── node_modules
├── node_modules
├── package.json
├── pnpm-lock.yaml
├── pnpm-workspace.yaml
├── Dockerfile
├── docker-compose.base.yaml
└── docker-compose.yml
```

## What I already tried

Install dependencies on docker build time and create a volume for `node_modules` in order to keep these folders on mount.

_docker-compose.base.yml_
```yml
services:
    base:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/apps/api/node_modules
            # ...other volumes configuration
        command: 'pnpm install'
```

_docker-compose.yml_
```yml
services:
    services:                
        api:
            extends:
                service: base
                file: docker-compose.base.yml
            command: pnpm --filter client dev

    ...other services configuration
```

_Dockerfile_
```
FROM node:17-buster
ARG PNPM_VERSION=7.14.2
RUN npm install -g pnpm@${PNPM_VERSION}

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

COPY apps/api/package.json apps/api/
COPY apps/client/package.json apps/client/
COPY libs/common/package.json libs/common/

RUN pnpm install

COPY . .
```

This works pretty well. pnpm's store is used and shared between the different docker services.
However, as `node_modules` folders are defined as specific volumes (in order to be present on mount), they're not synchronized with my local machine and this result into empty `node_modules` folders locally. In that case, IDE is struggling and cannot resolve dependencies locally.

I read a lot of articles about it ([this](https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds/32785014#32785014) or [this](https://dev.to/yamalight/comment/8a8c) or [this](https://stackoverflow.com/questions/51097652/install-node-modules-inside-docker-container-and-synchronize-them-with-host))
This looks like a common issue and some people are tricking the build/mount phase. Rather than creating `node_modules` volumes, they're copying the dependencies folders post build, [as follow](https://stackoverflow.com/a/52092711/6065476). This could work with a standard package manager (like npm or yarn) but not with pnpm. Indeed, the dependencies store is living at the root of the docker instance and symlinks that are made on it wouldn't be accessible from the local machine.

Other things I've seen that I don't think can be a viable solution:
- Run `pnpm install` each time I run a container rather than on build time
- Using an IDE feature as https://code.visualstudio.com/docs/devcontainers/containers. Could work but I don't want to rely on that.

I already had a look on the follwing issues without any results unfortunately:
- https://github.com/pnpm/pnpm/issues/3114
- https://github.com/pnpm/pnpm/issues/1637

What would be the best option with pnpm to synchronize `node_modules` folders that are installed on docker with my local machine ?

Thanks a lot for your help (:
