### DISCUSSION TITLE
The command `karma init` does not work for `pnpm` on an Angular project

### DISCUSSION THREAD

**Discussion by gusbemacbe** [pnpm/pnpm#5767] [Q&A] [answered]
Hello!

- I use Endeavour Linux OS. 
- Angular version is 15.0.2.
- `node` version is 18.12.1. 
- `pnpm` version is 7.18.4.

1. I installed `nvm` and ran the commands `nvm install 18` and nvm alias default 18`.
2. I ran the command `curl -fsSL https://get.pnpm.io/install.sh | sh -`.
3. I ran the command `pnpm i -g @angular/cli`. 
4. I ran the command to create a new Angular project, using `pnpm` as a package manager:

     ```sh
     ng new angular-fonts --directory angular-fonts --package-manager=pnpm
    ```

5. Then I ran `pnpm i`.
6. I replaced `package.json` with `package.yaml`, using the command `yq -p json -o yaml package.json > package.yaml`
7. I ran `npx karma init` and received the error following:

    ```
    node:internal/modules/cjs/loader:998
    throw err;
    ^

    Error: Cannot find module './build/index.cjs'
    Require stack:
    - /home/gus/Testes/angular-fonts/node_modules/.pnpm/yargs@16.2.0/node_modules/yargs/index.cjs
    - /home/gus/Testes/angular-fonts/node_modules/.pnpm/karma@6.4.1/node_modules/karma/lib/cli.js
    - /home/gus/Testes/angular-fonts/node_modules/.pnpm/karma@6.4.1/node_modules/karma/bin/karma
        at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
        at Module._load (node:internal/modules/cjs/loader:841:27)
        at Module.require (node:internal/modules/cjs/loader:1061:19)
        at require (node:internal/modules/cjs/helpers:103:18)
        at Object.<anonymous> (/home/gus/Testes/angular-fonts/node_modules/.pnpm/yargs@16.2.0/node_modules/yargs/index.cjs:5:30)
        at Module._compile (node:internal/modules/cjs/loader:1159:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
        at Module.load (node:internal/modules/cjs/loader:1037:32)
        at Module._load (node:internal/modules/cjs/loader:878:12)
        at Module.require (node:internal/modules/cjs/loader:1061:19) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/home/gus/Testes/angular-fonts/node_modules/.pnpm/yargs@16.2.0/node_modules/yargs/index.cjs',
        '/home/gus/Testes/angular-fonts/node_modules/.pnpm/karma@6.4.1/node_modules/karma/lib/cli.js',
        '/home/gus/Testes/angular-fonts/node_modules/.pnpm/karma@6.4.1/node_modules/karma/bin/karma'
      ]
    }

    Node.js v18.12.1
    ````

Here is my `package.yaml`:

```yaml
name: angular-fonts
description: Testing to load the third party fonts relative path in Angular
author: Gustavo Costa
license: MIT
private: true
version: 0.0.0
scripts:
  ng: ng
  start: ng serve
  build: ng build
  watch: ng build --watch --configuration development
  test: export CHROME_BIN="google-chrome-unstable" && ng test
dependencies:
  '@angular/animations': ^15.0.2
  '@angular/common': ^15.0.2
  '@angular/compiler': ^15.0.2
  '@angular/core': ^15.0.2
  '@angular/forms': ^15.0.2
  '@angular/platform-browser': ^15.0.2
  '@angular/platform-browser-dynamic': ^15.0.2
  '@angular/router': ^15.0.2
  rxjs: ~7.5.7
  tslib: ^2.4.1
  zone.js: ~0.12.0
devDependencies:
  '@angular-devkit/build-angular': ^15.0.2
  '@angular/cli': ~15.0.2
  '@angular/compiler-cli': ^15.0.2
  '@types/jasmine': ~4.3.1
  jasmine-core: ~4.5.0
  karma: ^6.4.1
  karma-chrome-launcher: ~3.1.1
  karma-coverage: ~2.2.0
  karma-edge-launcher: ^0.4.2
  karma-firefox-launcher: ^2.1.2
  karma-jasmine: ~5.1.0
  karma-jasmine-html-reporter: ~2.0.0
  typescript: ~4.8.4
```
