### DISCUSSION TITLE
Can we cache the node-modules folder to run dependencies in pipelines?

### DISCUSSION THREAD

**Discussion by TechWatching** [pnpm/pnpm#6374] [Q&A] [answered]
I am writing a CI pipeline (GitHub Actions) that uses dependencies of my project (like vitest, eslint, ....) to ensure the quality of the code. All these dependencies will be run in a different job than the job that install the dependencies and runs the build. So I would rather avoid repeating the install step on each job (just do it on the job that builds the project) by caching the node-modules directory so that the dependencies are available to be used.

In the pnpm documentation it's suggested to cache only the pnpm store (that's what the setup-node action does), but nothing is mentioned about the node-modules. Is there any reason why caching the node-modules directory would be a problem?

By the way is pnpm/action-setup still the recommended way of setting up pnpm in a GitHub runner, or is `corepack enable` the way to go?

**Comment by zkochan** [comment, marked as answer]
> By the way is pnpm/action-setup still the recommended way of setting up pnpm in a GitHub runner, or is corepack enable the way to go?

Maybe, I did not think about it. You can for sure use `corepack` instead.

> In the pnpm documentation it's suggested to cache only the pnpm store (that's what the setup-node action does), but nothing is mentioned about the node-modules. Is there any reason why caching the node-modules directory would be a problem?

Caching sometimes breaks the symlinks, so if you use the default "isolated" node_modules layout, then the restored cache might not work, but I am not sure it is the case on every CI. Also, if you cache node_modules and the store separately and then run `pnpm install`, then pnpm might relink files from node_modules to the store (to save disk space). In that case it doesn't make a lot of sense to cache node_modules. You can check that. If it will relink files, it will print about it to the console.

> So I would rather avoid repeating the install step on each job (just do it on the job that builds the project) by caching the node-modules directory so that the dependencies are available to be used.

If you won't run install again, then it might be OK.

**Reply by PatrikBird** [reply]
I think it would help if this information could go into https://pnpm.io/continuous-integration - I can try to write a few words and create a PR if you want :)

**Comment by kopach** [comment]
If you cache just `node_modules` and then do not run `pnpm install` during cache restore - everything works just fine.

**Note:** important to use exact keys (not `lax`) to restore cache
Also, some dependencies store binaries outside `node_modules` during `postinstall` (like [cypress](https://docs.cypress.io/guides/continuous-integration/introduction#Caching)) so you want to cache that also since there won't be `pnpm install` thus `postinstall` during cache restore

Something like this (with GH action)
```yml
    - name: Restore pnpm cache (if any)
      id: pnpm_cache
      uses: cache/restore@v4
      with:
        path: |
          ~/.cache/Cypress
          node_modules
        key: ${{ runner.os }}-dependencies-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install dependencies
      shell: bash
      if: steps.pnpm_cache.outputs.cache-hit != 'true'
      run: |
        pnpm install

    - name: Save pnpm cache (if changed)
      uses: cache/save@v4
      if: steps.pnpm_cache.outputs.cache-hit != 'true'
      with:
        path: |
          ~/.cache/Cypress
          node_modules
        key: ${{ steps.pnpm_cache.outputs.cache-primary-key }}
```
