### DISCUSSION TITLE
pnpm workspace commands are insanely slower when dockerized

### DISCUSSION THREAD

**Discussion by Geddard** [pnpm/pnpm#6394] [Q&A]
Hi there, I can't figure out why this is happening for the life of me.

I have a repo already setup with only Strapi, a postgress container and it works great by itself, it starts the db service and the strapi backend in something like 10s to have localhost:1337 available, but when I try to move this repo to be a package inside a monorepo, the same commands take up to 2 minutes to run :/

In the original strapi-cms repository I have:

Dockerfile

```
FROM node:16
# Dependencies
RUN apt-get update && apt-get install libvips-dev -y
RUN npm install -g pnpm

# Environment

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# Create app directory

WORKDIR /opt/
COPY .npmrc ./package.json ./pnpm-lock.yaml ./


ENV PATH /opt/node_modules/.bin:$PATH
RUN pnpm config set network-timeout 600000 -g
RUN pnpm install --frozen-lockfile 

WORKDIR /opt/app
COPY ./ .

RUN pnpm build

EXPOSE 1337

CMD ["pnpm", "dev"]

```

and docker-compose.yml

```
version: "3"
services:
  strapi:
    container_name: strapi
    build: .
    image: mystrapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./pnpm-lock.yaml:/opt/pnpm-lock.yaml
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    image: postgres:15.0-alpine
    container_name: strapiDB
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
```

This is all pretty much copy-pasted from the Strapi guide to dockerize the app, I just modified it a bit to use `pnpm`, works great, first build takes longer due to dependencies and then subsequent ones take 10s max to be up and running.

Now, when I try to move this to my monorepo with the frontend app, which would have the following structure:

```
myApp/
 packages/ 
   strapi-cms/ 
   graphql/ 
   client/ // nextjs app
```

For now I'm only trying to get the `strapi-cms` package running with docker, 

I copied most of the original `docker-compose.yml` but updated the volumes paths adding `packages/cms` to find them and added the build section like

```
build:
      context: .
      dockerfile: Dockerfile
      target: strapi
```

And the dockerfile in the monorepo looks like this:

```
# Base setup

FROM node:16 as base

RUN npm install -g pnpm

WORKDIR /app
COPY pnpm-lock.yaml package.json .npmrc pnpm-workspace.yaml ./

COPY ./packages/cms/ ./packages/cms/ 
COPY ./packages/client/ ./packages/client/ 
COPY ./packages/graphql/ ./packages/graphql/ 

ENV PATH /opt/node_modules/.bin:$PATH
RUN pnpm config set network-timeout 600000 -g
RUN pnpm install --frozen-lockfile --prod

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# Strapi service

FROM base as strapi
RUN apt-get update && apt-get install libvips-dev -y

RUN pnpm cms build
EXPOSE 1337
CMD ["pnpm", "cms", "dev"]
```

I have this in my monorepo package.json to run the pnpm commands in docker

```
  "scripts": {
    "client": "pnpm --filter client",
    "gql": "pnpm --filter graphql",
    "cms": "pnpm --filter cms",
    "lint": "pnpm -r lint",
    "dev": "pnpm gql build && pnpm client dev"
  },
```

and finally, my .dockerignore

```
/**/*/.env
/**/*/.env.*
/**/*/README.md
/**/*/.git
/**/*/.gitignore
/**/*/npm-debug.log
/**/*/.dockerignore
/**/*/Dockerfile

/**/*/node_modules
/**/*/test
/**/*/dist
/**/*/.tmp/
/**/*/.cache/
/**/*/.git/
/**/*/build/
/**/*/data/
```

This works.
Strapi is built and it runs, but it obviously takes much longer in every aspect as there are more dependencies for other packages. (I guess it's normal?)

But for some reason the strapi container takes up to two minutes to execute the `pnpm cms dev` command, and I can't figure out why, I've researched for around 2 days now without luck, any suggestions on how to speed this up? or is it just how pnpm works with monorepos?

Thanks and kind regards.
