### DISCUSSION TITLE
pnpm.auditConfig.ignoreCves and vulnerabilities without a CVE

### DISCUSSION THREAD

**Discussion by pateljay1397** [pnpm/pnpm#6473] [Q&A]
The https://pnpm.io/package_json#pnpmauditconfigignorecves specifically targets CVEs to ignore in pnpm audit.

Some vulnerabilities, such as https://github.com/advisories/GHSA-36jr-mh4h-2g58, show up in pnpm audit but have no assigned CVE. we tried with GHSA but that does not seem to work.
Does anyone know if that's expected, or is this a bug?
If it is not a bug, then what should be the recommended workaround for it (ignore pnpm audit using GHSA).

**Comment by janhoy** [comment]
I too have this question

**Comment by JE4GLE** [comment]
For anyone else having this question, use `auditConfig.ignoreGhsas`:

```yaml
auditConfig:
  ignoreGhsas:
    - GHSA-42xw-2xvc-qx8m
    - GHSA-4w2v-q235-vp99
    - GHSA-cph5-m8f7-6c5x
    - GHSA-vh95-rmgr-6w4m
```

https://pnpm.io/cli/audit#auditconfigignoreghsas
