### DISCUSSION TITLE
pnpm update peers

### DISCUSSION THREAD

**Discussion by Enrice** [pnpm/pnpm#6487] [Q&A]
I tried to pin react for upstream updates as a peer dependency of "react-intl": "6.0.4" in the workspace root on "^17.0.2" for my packages:
```
"dependencies": {
  "react": "^17.0.2"
},
```
Assume that yyy has react 17.0.2 as dependency.
When I do "pnpm install" I get the following in my pnpm-lock.yaml:
```
packages/xxx:
  dependencies:
    yyy:
      specifier: ~1.0.0
      version: 1.0.0
    react-intl:
      specifier: 6.0.4
      version: 6.0.4(react@17.0.2)
```

As resolve-peers-from-workspace-root is true per default in pnpm 8.3.1 I expected to have this peer dependency stay on this version in the lockfile when updating some dependencies where react-intl is a dependency with "pnpm update yyy". But no, I got the following:

```
packages/xxx:
  dependencies:
    yyy:
      specifier: ~1.0.1
      version: 1.0.1
    react-intl:
      specifier: 6.0.4
      version: 6.0.4(react@18.2.0)
```

Note the changed peer dependency in the lock file. It seems that "pnpm update" does not respect this setting. How can I achieve react to stay on 17.0.2 as I had previously installed it? What actually DID work was adding it as a direct dependency to xxx. I would like to refrain from that, if possible...
