### DISCUSSION TITLE
`pnpm publish -r` always leads to ENEEDAUTH

### DISCUSSION THREAD

**Discussion by openscript** [pnpm/pnpm#7402] [Q&A]
I'm trying to publish a few packages from my monorepo to NPM. I've got this Github Workflow:

```yml
name: Deploy to registries

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  build-and-deploy:
    name: Build and deploy NPM package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Configure node for NPM as registry
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare packages
        run: pnpm prepublish

      - name: Set registry
        run: "echo \"//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}\" >> .npmrc"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish packages on NPM
        run: pnpm publish -r --no-git-checks
```

Unfortunately I always get the following error:

```
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://registry.npmjs.org/
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

I've tried so many things:
- Setting the registry in the `setup-node` action
- Using `pnpm config set`
- Removing the `.npmrc`

With NPM it always works, but then I need to write a script going through all the packages.

Does somebody have an idea what I'm doing wrong?

**Comment by jacksonneal** [comment]
Any resolution to this?

**Reply by openscript** [reply]
I publish now with https://github.com/changesets/changesets and haven't had a problem since.

**Reply by jacksonneal** [reply]
Any chance you could share a snippet?  I've duplicated their README but am still seeing weirdness where it can't find the right registry or 403s with permissions.

**Reply by jacksonneal** [reply]
This is my workflow job:

```
  publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      ...
      - run: |
          cat << EOF > "$HOME/.npmrc"
            @jacksonneal:registry=https://npm.pkg.github.com/
            //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: changesets/action@v1
        with:
          publish: pnpm publish -r --access restricted --no-git-checks --registry https://npm.pkg.github.com/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

which results in:

```
[changeset-release/main 8e9427e] Version Packages
 3 files changed, 7 insertions(+), 6 deletions(-)
 delete mode 100644 .changeset/healthy-dingos-yawn.md
/usr/bin/git push origin HEAD:changeset-release/main --force
remote: Permission to jacksonneal/standards.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/jacksonneal/standards/': The requested URL returned error: 403
```

I imagine I am missing a permission?  I am also confused about where the registry is supposed to be set.

**Reply by openscript** [reply]
Here is a monorepo and multiple npm packages published: https://github.com/timelet/timelet

It uses nx, pnpm and changesets.

**Reply by jacksonneal** [reply]
Thank you!  Pushing packages to the registry is now working.  Oddly I am not seeing releases/tags created in the repo.

**Reply by jacksonneal** [reply]
Here is the repo if you can spot something https://github.com/jacksonneal/standards/tree/main

**Reply by openscript** [reply]
Maybe it has something to do because your root package is private. I've been struggling with the same before: https://github.com/changesets/changesets/discussions/1193

**Reply by jacksonneal** [reply]
Thanks for taking a look.  That doesn't seem to have fixed it.  I think there something wrong with the tag creation even though it looks successful:

```
npm notice
npm notice Publishing to https://npm.pkg.github.com/ with tag latest and default access
+ @jacksonneal/ts-standard@0.0.0
/usr/bin/git push origin --tags
Everything up-to-date
```

Maybe I should be creating a tag, changesets doesn't?

**Reply by openscript** [reply]
Ah, maybe because you are not calling changeset tag?

https://github.com/timelet/timelet/blob/ed6e3d4146404cd4ce1c138163af7f5abed4cca2/.github/workflows/cd-publish.yml#L40
https://github.com/timelet/timelet/blob/ed6e3d4146404cd4ce1c138163af7f5abed4cca2/package.json#L16

**Reply by jacksonneal** [reply]
This works when I run locally but still can't create/push the tags in CI:

    "ci:version": "pnpm changeset version && pnpm changeset tag",
    "ci:publish": "pnpm publish -r && git push --follow-tags"
    
    
   Maybe the bot doesn't have permission to push tags?
   
   For instance, I see these logs but the tag 0.0.2 is nowhere to be found:
   
   ```
   Run changesets/action@v1
setting git user
/usr/bin/git config user.name "github-actions[bot]"
/usr/bin/git config user.email "github-actions[bot]@users.noreply.github.com"
setting GitHub credentials
No changesets found, attempting to publish any unpublished packages to npm
Found existing user .npmrc file
Didn't find existing auth token for the npm registry in the user .npmrc file, creating one
/home/runner/setup-pnpm/node_modules/.bin/pnpm publish -r
npm notice
npm notice 📦  @jacksonneal/ts-standard@0.0.2
npm notice Tarball Contents
npm notice 135B CHANGELOG.md
npm notice 36B README.md
npm notice 228B ex/filter.ex.ts
npm notice 348B ex/shared.ex.ts
npm notice 303B ex/type.ex.ts
npm notice 690B package.json
npm notice 682B src/filter.ts
npm notice 146B src/index.ts
npm notice 626B src/type.ts
npm notice 627B test/filter.test.ts
npm notice 576B tsconfig.json
npm notice 65B tsconfig.vite.json
npm notice 600B vite.config.ts
npm notice Tarball Details
npm notice name: @jacksonneal/ts-standard
npm notice version: 0.0.2
npm notice filename: jacksonneal-ts-standard-0.0.2.tgz
npm notice package size: 2.3 kB
npm notice unpacked size: 5.1 kB
npm notice shasum: 8199bceaff47732f69655ad486c22a7173a42909
npm notice integrity: sha5[12](https://github.com/jacksonneal/ts-standards/actions/runs/10895367302/job/30233512936#step:6:13)-31d64R80BMuXp[...]15ipvFHliollA==
npm notice total files: 13
npm notice
npm notice Publishing to https://npm.pkg.github.com/ with tag latest and default access
+ @jacksonneal/ts-standard@0.0.2
/usr/bin/git push origin --tags
Everything up-to-date
```

**Reply by jacksonneal** [reply]
Figured it out! I did need to run changeset tag, but I was putting it in the wrong spot.  

These are my package.json scripts:
```
    "ci:version": "pnpm changeset version",
    "ci:publish": "pnpm changeset tag && pnpm publish -r"
```

And I have this CI step:
```
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup
      - run: just ts-standard-install
      - run: |
          cat << EOF > "$HOME/.npmrc"
            @jacksonneal:registry=https://npm.pkg.github.com/
            //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: changesets/action@v1
        with:
          version: pnpm ci:version
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Works wonderfully.  Thanks for the assistance!
