### DISCUSSION TITLE
Docker Dev Containers - What is your setup method?

### DISCUSSION THREAD

**Discussion by SStranks** [pnpm/pnpm#7469] [Q&A]
I can't find much solid advice on development containers in Docker when using PNPM. Everything seems to focus on docker images for production and deployment.

When using NPM, one could use docker bindmounts and map across the entire service you were working on. 

```
# app folder structure:
├── backend
    ├── node_modules
    ├── server
    ├── package.json
├── frontend
├── docker-compose.override.yml

# docker-compose.override.yml
services:
  node-api:
    working_dir: /backend
    volumes:
      - ./backend:/backend:ro
```

This doesn't work in a PNPM monorepo where the service node_modules has symlinks pointing to the root node_modules and pnpm-store. However, if you map across the root node_modules as well it seems to work.

```
services:
  node-api:
    working_dir: /backend
    volumes:
      - ./backend:/backend:ro
      - ../../node_modules:/node_modules:ro
```

My question is, is this the best way to go about things? 

I tried experimenting with building docker images and using the 'deploy' command, with --dev flag, however it didn't bundle everything required e.g. 'nodemon' was missing its own dependencies.
