### DISCUSSION TITLE
Moving settings to `pnpm-workspace.yaml`

### DISCUSSION THREAD

**Discussion by zkochan** [pnpm/pnpm#9037] [Ideas]
Currently we use 3 files for configuring pnpm:

* We use `.npmrc` for most of the settings. Mostly simple settings but also some that can be arrays
* We also load settings from the `pnpm` field in `package.json`. These are mostly more complex settings with arrays and objects.
* We also load catalogs from `pnpm-workspace.yaml`

We need to stop storing settings in `package.json` as it breaks the fetch command. See related issue: https://github.com/pnpm/pnpm/issues/9033. Moving all settings to the `.npmrc` ini file is not convenient. The best approach seems to be to move all the settings to `pnpm-workspace.yaml`. On top of the settings from `package.json` we may also move all the pnpm-specific settings from `.npmrc` and only keep auth related settings in `.npmrc` for npm compatibility.

Some settings may be project-specific. Instead of creating separate configuration files for projects in the workspace, we could create configuration overrides in the root `pnpm-workspace.yaml`. For instance:

```yaml
packages:
  - "**"
hoistPattern:
  - eslint
configOverrides:
  - globs:
      - back-end/**
    settings:
      executionEnv:
        nodeVersion: 16.16.0
```

Related PRs:
- https://github.com/pnpm/pnpm/pull/9121
- https://github.com/pnpm/pnpm/pull/9211
- https://github.com/pnpm/pnpm/pull/9316
- https://github.com/pnpm/pnpm/pull/9317
- https://github.com/pnpm/pnpm/pull/9325

npm CLI will disallow 3rd party settings in `.npmrc` from v12. Related issue: https://github.com/pnpm/pnpm/issues/9232
