### DISCUSSION TITLE
Azure DevOps and caching

### DISCUSSION THREAD

**Discussion by stevebeauge** [pnpm/pnpm#9496] [Q&A]
Hi,

In the [Azure Devops guide](https://pnpm.io/next/continuous-integration#azure-pipelines), the cache operation includes `pnpm-lock.yaml`:

```yaml
steps:
  - task: Cache@2
    inputs:
      key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
      path: $(pnpm_config_cache)
    displayName: Cache pnpm
```

As far as I understand, the cache will be invalidated everytime the lock file changes. 

That means the whole store will be redownloaded again if a single package in the whole tree changes. Which is very frequent.

Because pnpm is smart enough to download only missing packages, shouldn't `pnpm-lock.yaml` be removed from the input keys of the cache operation ?

If wasting space is a concern, maybe a simple call to `pnpm store prune` after the `pnpm install` command may be enough?
