### ISSUE TITLE
Include integrity checksums when resolution=tarball

### ISSUE THREAD

**Issue by adisbladis** [pnpm/pnpm#1035]
It would be useful to include integrity hashes in `shrinkwrap.yaml`.

Not only can this provide tamper evidence in case of upstream tarballs changing it's also useful for other things.
I need this in my project [pnpm2nix](https://github.com/adisbladis/pnpm2nix/) (nix requires all sources to have known checksums).

### Expected behavior:
```
github.com/debris/bignumber.js/94d7146671b9719e00a09c29b01a691bc85048c2:
  dev: false
  name: bignumber.js
  resolution:
    tarball: 'https://codeload.github.com/debris/bignumber.js/tar.gz/94d7146671b9719e00a09c29b01a691bc85048c2'
  version: 2.0.7
```

### Actual behavior:
```
github.com/debris/bignumber.js/94d7146671b9719e00a09c29b01a691bc85048c2:
  dev: false
  name: bignumber.js
  resolution:
    tarball: 'https://codeload.github.com/debris/bignumber.js/tar.gz/94d7146671b9719e00a09c29b01a691bc85048c2'
    integrity: sha256-0s25j91rlba07i2y6bkhg9fgjmgy77lmaj9szp0nin7mzqgigdy1
  version: 2.0.7
```
