### ISSUE TITLE
Save non-standard tarball URLs in shrinkwrap.yaml

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1072]
To reduce the size of `shrinkwrap.yaml` we don't save the tarball URLs of packages from `registry.npmjs.org`. We can create their tarballs URLs if we know their name and version (see related code in supi: https://github.com/pnpm/supi/blob/9eb87ce9f296097f1368f150725533b3933a1d60/src/resolveDependencies.ts#L227).

However, some packages have weird tarball URLs. For instance, the tarball URL of `esprima-fb@3001.1.0-dev-harmony-fb` is https://registry.npmjs.org/esprima-fb/-/esprima-fb-3001.0001.0000-dev-harmony-fb.tgz, so we have to save its tarball URL in shrinkwrap.yaml

Currently it would be saved to `shrinkwrap.yaml` like this:

```yaml
  /esprima-fb/3001.1.0-dev-harmony-fb:
    dev: true
    engines:
      node: '>=0.4.0'
    resolution:
      integrity: sha1-t303q8046gt3Qmu4vCkizmtCZBE=
```

It should be saved like this:

```yaml
  /esprima-fb/3001.1.0-dev-harmony-fb:
    dev: true
    engines:
      node: '>=0.4.0'
    resolution:
      integrity: sha1-t303q8046gt3Qmu4vCkizmtCZBE=
      tarball: https://registry.npmjs.org/esprima-fb/-/esprima-fb-3001.0001.0000-dev-harmony-fb.tgz
```
