### ISSUE TITLE
Doesn't handle dependencies with unspecified version

### ISSUE THREAD

**Issue by davej** [pnpm/pnpm#1104]
### Code to reproduce the issue:

Create a `package.json` like the file below and then run `pnpm install`

```js
{
  "name": "example",
  "version": "1.0.0",
  "description": "example",
  "main": "index.js",
  "devDependencies": {
    "pug": "",
  },
  "dependencies": {}
}
```

### Expected behavior:

Should install the current version of Pug. Tested and working using npm.

### Actual behavior:

```
  772 error pnpm: 
    message: 
      name: "YAMLException"
      reason: "unacceptable kind of an object to dump [object Undefined]"
      message: "unacceptable kind of an object to dump [object Undefined]"
    err: 
      name: "YAMLException"
      message: "unacceptable kind of an object to dump [object Undefined]"
      stack: "YAMLException: unacceptable kind of an object to dump [object Undefined]\n    at writeNode (/Users/dave/n/lib/node_modules/pnpm/lib/node_modules/js-yaml/lib/js-yaml/dumper.js:748:13)\n    at writeBlockMapping (/Users/dave/n/lib/node_modules/pnpm/lib/node_modules/js-yaml/lib/js-yaml/dumper.js:627:10)\n    at writeNode (/Users/dave/n/lib/node_modules/pnpm/lib/node_modules/js-yaml/lib/js-yaml/dumper.js:720:9)\n    at writeBlockMapping (/Users/dave/n/lib/node_modules/pnpm/lib/node_modules/js-yaml/lib/js-yaml/dumper.js:627:10)\n    at writeNode (/Users/dave/n/lib/node_modules/pnpm/lib/node_modules/js-yaml/lib/js-yaml/dumper.js:720:9)\n    at dump (/Users/dave/n/lib/node_modules/pnpm/lib/node_modules/js-yaml/lib/js-yaml/dumper.js:809:7)\n    at Object.safeDump (/Users/dave/n/lib/node_modules/pnpm/lib/node_modules/js-yaml/lib/js-yaml/dumper.js:815:10)\n    at Object.write (/Users/dave/n/lib/node_modules/pnpm/lib/node_modules/pnpm-shrinkwrap/lib/write.js:45:26)\n    at /Users/dave/n/lib/node_modules/pnpm/lib/node_modules/supi/lib/api/install.js:399:41\n    at Generator.next (<anonymous>)"
```

### Additional information:

macOS 10.12
node v8.9.1
Bug also occurs with Supi.
