### ISSUE TITLE
EINTEGRITY issues on Ubuntu 16.04

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1166]
```
  20157 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/acorn/5.5.3"
    pkgVersion: "5.5.3"
  20158 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/acorn-dynamic-import/2.0.2"
    pkgVersion: "2.0.2"
  20159 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/ajv/5.5.2"
    pkgVersion: "5.5.2"
  20160 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/async/2.6.0"
    pkgVersion: "2.6.0"
  20161 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/enhanced-resolve/3.4.1"
    pkgVersion: "3.4.1"
  20162 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/escope/3.6.0"
    pkgVersion: "3.6.0"
  20163 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/interpret/1.1.0"
    pkgVersion: "1.1.0"
  20164 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/json-loader/0.5.7"
    pkgVersion: "0.5.7"
  20165 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/json5/0.5.1"
    pkgVersion: "0.5.1"
  20166 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/loader-runner/2.3.0"
    pkgVersion: "2.3.0"
  20167 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/loader-utils/1.1.0"
    pkgVersion: "1.1.0"
  20168 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/memory-fs/0.4.1"
    pkgVersion: "0.4.1"
  20169 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/mkdirp/0.5.1"
    pkgVersion: "0.5.1"
  20170 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/node-libs-browser/2.1.0"
    pkgVersion: "2.1.0"
  20171 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/source-map/0.5.7"
    pkgVersion: "0.5.7"
  20172 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/supports-color/4.5.0"
    pkgVersion: "4.5.0"
  20173 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/tapable/0.2.8"
    pkgVersion: "0.2.8"
  20174 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/uglifyjs-webpack-plugin/0.4.6"
    pkgVersion: "0.4.6"
  20175 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/watchpack/1.6.0"
    pkgVersion: "1.6.0"
  20176 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/webpack-sources/1.1.0"
    pkgVersion: "1.1.0"
  20177 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/yargs/8.0.2"
    pkgVersion: "8.0.2"
  20178 debug pnpm:progress:
    pkgId: "registry.npmjs.org/ajv-keywords/2.1.1"
    status: "fetched"
  20179 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/ajv-keywords/2.1.1"
    pkgVersion: "2.1.1"
  20180 debug pnpm:progress:
    status: "fetching_started"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    size: 446614
    attempt: 2
  20181 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 2759
  20182 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 5518
  20183 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 8277
  20184 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 11036
  20185 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 13795
  20186 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 16073
  20187 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 18832
  20188 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 21591
  20189 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 24350
  20190 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 27109
  20191 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 29868
  20192 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 32457
  20193 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 48841
  20194 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 51600
  20195 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 54359
  20196 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 57118
  20197 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 59877
  20198 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 62636
  20199 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 64937
  20200 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 67696
  20201 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 70455
  20202 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 73214
  20203 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 75973
  20204 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 78732
  20205 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 81321
  20206 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 97705
  20207 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 100464
  20208 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 103223
  20209 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 105982
  20210 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 108741
  20211 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 111500
  20212 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 114089
  20213 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 116848
  20214 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 119607
  20215 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 122366
  20216 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 125125
  20217 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 127884
  20218 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 130473
  20219 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 146857
  20220 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 149616
  20221 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 152375
  20222 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 155134
  20223 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 157893
  20224 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 160652
  20225 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 163241
  20226 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 166000
  20227 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 168759
  20228 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 171518
  20229 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 174277
  20230 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 177036
  20231 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 179625
  20232 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 196009
  20233 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 198768
  20234 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 201527
  20235 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 204286
  20236 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 207045
  20237 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 209804
  20238 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 212393
  20239 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 215152
  20240 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 217911
  20241 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 220670
  20242 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 223429
  20243 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 226188
  20244 debug pnpm:progress:
    status: "fetching_progress"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    downloaded: 228777
  20245 debug pnpm:progress:
    status: "fetching_started"
    pkgId: "registry.npmjs.org/@storybook/ui/3.4.3"
    size: 446614
    attempt: 3
  20246 error pnpm: "Fetching registry.npmjs.org/@storybook/ui/3.4.3 failed!"
  20247 error pnpm:
    message:
      code: "EINTEGRITY"
      found: "sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg=="
      expected:
        - "sha512-AZBsdw2rlm68X24jVmsTSlwOnqvYlTld+jeFKVpUTW6LdaTTF6xlqhYMiqBb3ykYeLP7/tyIcJkZJvZIGAoBZQ=="
      algorithm: "sha512"
      sri: "sha512-AZBsdw2rlm68X24jVmsTSlwOnqvYlTld+jeFKVpUTW6LdaTTF6xlqhYMiqBb3ykYeLP7/tyIcJkZJvZIGAoBZQ=="
      attempts: 3
      resource: "https://registry.npmjs.org/@storybook/ui/-/ui-3.4.3.tgz"
    err:
      name: "Error"
      message: "sha512-AZBsdw2rlm68X24jVmsTSlwOnqvYlTld+jeFKVpUTW6LdaTTF6xlqhYMiqBb3ykYeLP7/tyIcJkZJvZIGAoBZQ== integrity checksum failed when using sha512: wanted sha512-AZBsdw2rlm68X24jVmsTSlwOnqvYlTld+jeFKVpUTW6LdaTTF6xlqhYMiqBb3ykYeLP7/tyIcJkZJvZIGAoBZQ== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)"
      code: "EINTEGRITY"
      stack: "Error: sha512-AZBsdw2rlm68X24jVmsTSlwOnqvYlTld+jeFKVpUTW6LdaTTF6xlqhYMiqBb3ykYeLP7/tyIcJkZJvZIGAoBZQ== integrity checksum failed when using sha512: wanted sha512-AZBsdw2rlm68X24jVmsTSlwOnqvYlTld+jeFKVpUTW6LdaTTF6xlqhYMiqBb3ykYeLP7/tyIcJkZJvZIGAoBZQ== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)\n    at Transform.on (/usr/local/lib/node_modules/pnpm/lib/node_modules/ssri/index.js:312:19)\n    at emitNone (events.js:111:20)\n    at Transform.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1056:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"
```

Then at the end of the install:

```
ERROR  ENOENT: no such file or directory, open '/home/ubuntu/.pnpm-store/2/registry.npmjs.org/@storybook/ui/3.4.3/_tmp_18937_cf713905c1b2af4b365fb3b781abe2e1/package.json'
at org/

┌──────────────────────────────────────────────────────────┐
│                 pnpm update check failed                 │
│           Try running with sudo or get access            │
│           to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /home/ubuntu/.config │
└──────────────────────────────────────────────────────────┘
Error: ENOENT: no such file or directory, open '/home/ubuntu/.pnpm-store/2/registry.npmjs.org/@storybook/ui/3.4.3/_tmp_18937_cf713905c1b2af4b365fb3b781abe2e1/package.json'
```

And the next time I run the same install:

```
Resolving: total 1138, reused 0, downloaded 419
ERROR  ENOENT: no such file or directory, open '/home/ubuntu/.pnpm-store/2/registry.npmjs.org/@storybook/ui/3.4.3/_tmp_19299_7c7b9a6af396cc464124080cfc6273c8/package.json'
at org/

┌──────────────────────────────────────────────────────────┐
│                 pnpm update check failed                 │
│           Try running with sudo or get access            │
│           to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /home/ubuntu/.config │
└──────────────────────────────────────────────────────────┘
Error: ENOENT: no such file or directory, open '/home/ubuntu/.pnpm-store/2/registry.npmjs.org/@storybook/ui/3.4.3/_tmp_19299_7c7b9a6af396cc464124080cfc6273c8/package.json'
```

This also happened for `@turf/turf`.

The issue on npm was locked here: https://github.com/npm/npm/issues/16861

They say to upgrade npm...do we depend on npm packages related to fetching packages?

### Additional information:

 - `node -v` prints: 8.9.0
 - Windows, OS X, or Linux?: Ubuntu 16.04 running in VirtualBox 5.2.8.
