### ISSUE TITLE
How to cache pnpm packages for Gitlab CI?

### ISSUE THREAD

**Issue by NearAutomata** [pnpm/pnpm#1174]
In my Gitlab CI setup I am caching the `node_modules` folder as usual however I noticed that `pnpm` is redownloading all dependencies every time the pipeline is executed and not reusing a single one. Apparently `${HOME}/.npm` is empty during execution so this is not a folder that I can cache.

I'd like to know which other folders I have to cache in order to speed up the build and make pnpm reuse the downloaded packages on the next run of the CI.

**Comment by zkochan** [comment]
You should cache the store, that is at `~/.pnpm-store` by default. You could use a different location by using the [store](https://pnpm.js.org/docs/en/pnpm-install.html#store) config.

However, if you cache the store, then it will grow over time. So I suggest pruning the store before caching it, using the [pnpm store prune](https://pnpm.js.org/docs/en/pnpm-store.html#pnpm-store-prune) command.

To make installation faster, also turn off [store integrity](https://pnpm.js.org/docs/en/pnpm-install.html#verify-store-integrity) verification by running `npm set verify-store-integrity false` at the beginning of the build

**Comment by NearAutomata** [comment]
To my surprise though, `~/.pnpm-store` was an empty folder as well (at least the Gitlab caching tool did print a warning that there are no files) and the `store` variable I know from npm was undefined. Hence I have no clue where the files might have ended up.

**Comment by zkochan** [comment]
when the store variable is not set, the location should be `~/.pnpm-store` unless the homedir is not on the same disk on which installation is performed. Try a custom store location in that case by using the `store` config.

**Comment by NearAutomata** [comment]
Once I got some time to try it out, I will report my results.

**Comment by NearAutomata** [comment]
Alright I am surprised to see that it works all of a sudden. Even though I intended to cache the pnpm store the cached node_modules folder suffices for the time being. Apparently it took Gitlab a few runs of the CI to notice no more changes.

**Comment by soriyath** [comment]
It would be great to have a sample `.gitlab-ci.yml` file.

**Comment by zkochan** [comment]
we have some CI configuration example here: https://pnpm.js.org/en/continuous-integration

**Comment by chargome** [comment]
For anyone else struggling with setting up a reusable pnpm cache on a gitlab monorepo this might help:

```yml
stages:
  - prepare
  - test

default:
  image: node:lts-alpine
  cache: &cache
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .pnpm-store
      - ./node_modules
      - apps/web/node_modules
    policy: pull


before_script:
  - npm i -g pnpm
  - pnpm config set store-dir .pnpm-store

install:js:
  stage: prepare
  interruptible: true
  cache:
    <<: *cache
    policy: push
  script:
    - pnpm install

lint:web:
  stage: test
  needs:
    - job: install:js
      artifacts: false
  interruptible: true
  script:
    - pnpm run lint --filter @yourmonorepo/web
  rules:
    - changes:
      - apps/web/**/*
      - .gitlab-ci.yml
 
# ...rest of your ci

```

**Comment by the-ult** [comment]
> we have some CI configuration example here: https://pnpm.js.org/en/continuous-integration

Thanks for the examples. 👍 
However it would be nice if it would have multiple steps.
E.g.
- setup
- build
- test

etc

In that case. Should we cache `node_modules` or just run `pnpm i` on each step?

**Comment by chargome** [comment]
@the-ult fastest method is to cache your modules in your setup stage and pull it in all other stages

**Comment by the-ult** [comment]
aah thanks.
Yeah somehow the caching of `node_modules` is really slow in our pipeline.. zipping and uploading to S3
And in each step downloading from S3.
But I'm gonna give it a try.

Caching the `pnmp-store` and running `pnpm i` on each step is still a lot! faster than with `npm`. So already really happy with those results 👍

**Comment by manuman94** [comment]
Important note for those using Gitlab: You can't cache folders that aren't in the project folder. That's why it is necessary to choose a custom path for `pnpm-store`, contained in the project folder.

I was getting crazy with the message "no matching files". This StackOverflow answer was my source of information: https://stackoverflow.com/questions/53953122/gitlab-ci-cache-no-matching-files

Greetings.

**Comment by the-ult** [comment]
It is described on the pnpm site as well: https://pnpm.io/continuous-integration#gitlab-ci

**Comment by btd1337** [comment]
Add `before_script` section in global scope like this: 

```yml
image: node:18-alpine3.18

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - node_modules/
    - .pnpm-store/

before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store

stages:
  - build
  - lint
  - test
  - deploy

build:
  stage: build
  only:
    - merge_requests
    - staging
    - production
  script:
    - pnpm install
  tags:
    - shared

lint:code:
  stage: lint
  needs: [build]
  only:
    - merge_requests
    - staging
    - production
  script:
    - pnpm lint:quiet
  tags:
    - shared

[...]
```
