### ISSUE TITLE
ENOENT

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1293]
```
  40490 info pnpm:
    err:
      name: "Error"
      message: "ENOENT: no such file or directory, open '/Users/Vaughan/.pnpm-store/2/registry.npmjs.org/nopt/3.0.6/package/package.json'"
      code: "ENOENT"
      stack: "Error: ENOENT: no such file or directory, open '/Users/Vaughan/.pnpm-store/2/registry.npmjs.org/nopt/3.0.6/package/package.json'"
  40491 error pnpm:
    message:
      errno: -2
      code: "ENOENT"
      syscall: "open"
      path: "/Users/Vaughan/.pnpm-store/2/registry.npmjs.org/nopt/3.0.6/package/package.json"
      prefix: "/xxx/packages/xxx/protocol/xxx-protobufjs"
    err:
      name: "Error"
      message: "ENOENT: no such file or directory, open '/Users/Vaughan/.pnpm-store/2/registry.npmjs.org/nopt/3.0.6/package/package.json'"
      code: "ENOENT"
      stack: "Error: ENOENT: no such file or directory, open '/Users/Vaughan/.pnpm-store/2/registry.npmjs.org/nopt/3.0.6/package/package.json'"
```

These two files exist on disk by the time I look at the logs.

There seems to be a race condition somewhere...

### Additional information:

 - `node -v` prints: 8.9.0
 - Windows, OS X, or Linux?: macOS Sierra/High Sierra
