### ISSUE TITLE
Package "is-extglob" not being linked

### ISSUE THREAD

**Issue by nickpape-msft** [pnpm/pnpm#1305]
### Code to reproduce the issue:

I wasn't able to get a minimalist repro, and the repo that it does occur in contains a bunch of references to private packages.

Our shinkwrap contains:
```yaml
  /is-glob/3.1.0:
    dependencies:
      is-extglob: 2.1.1
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha1-e6WuJCF4BKxwcHuWkiVnSGzD6Eo=
```

### Actual behavior: "is-extglob" is not linked.

Oddly, it does appear in the store:

![image](https://user-images.githubusercontent.com/17131271/43165570-142ba79c-8f49-11e8-9471-df79e93698e4.png)

And it appears in the node_modules:

![image](https://user-images.githubusercontent.com/17131271/43165617-361a1370-8f49-11e8-94b9-a58b494df6b2.png)

But it is not linked by "is-glob"; 

![image](https://user-images.githubusercontent.com/17131271/43165683-638abad0-8f49-11e8-8ab9-dbbd78e2b1f8.png)

It's deterministic and occurs on a clean install.

The rush/pnpm log is here: 
[InstallLog.txt](https://github.com/pnpm/pnpm/files/2225385/InstallLog.txt)

### Additional information:

 - `node -v` prints: 8.9.4
 - Windows, OS X, or Linux?: Windows Server 2008 R2
