### ISSUE TITLE
`404 Not Found: @vjpr/geojson-utils0.1.0 (via https://registry.npmjs.org/@vjpr%2Fgeojson-utils0.1.0)`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1319]
_package.json_

```
    "geojson-utils": "npm:@vjpr/geojson-utils0.1.0",
```

_pnpm-debug.log_

```
   err: 
      name: "Error"
      message: "404 Not Found: @vjpr/geojson-utils0.1.0 (via https://registry.npmjs.org/@vjpr%2Fgeojson-utils0.1.0)"
      code: "ERR_PNPM_REGISTRY_META_RESPONSE_404"
      stack: "Error: 404 Not Found: @vjpr/geojson-utils0.1.0 (via https://registry.npmjs.org/@vjpr%2Fgeojson-utils0.1.0)\n    at /Users/Vaughan/nvm/versions/node/v8.9.0/pnpm-global/1/node_modules/.registry.npmjs.org/pnpm/2.13.1/node_modules/pnpm/lib/node_modules/@pnpm/npm-resolver/lib/pickPackage.js:103:25\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/Vaughan/nvm/versions/node/v8.9.0/pnpm-global/1/node_modules/.registry.npmjs.org/pnpm/2.13.1/node_modules/pnpm/lib/node_modules/@pnpm/npm-resolver/lib/pickPackage.js:4:58)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"
```

If I make a fresh new repo I don't see this error.

Looks like the url is messed up. https://registry.npmjs.org/@vjpr%2Fgeojson-utils0.1.0

Probably something to do with parsing aliases with `@scopes`.

---

EDIT: I am seeing same issue without scopes.

Maybe a general issue with aliases.
