### ISSUE TITLE
ENOENT during `pnpm m i`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1450]
```
  64151 error pnpm: 
    message: 
      errno: -2
      code: "ENOENT"
      syscall: "lstat"
      path: "/Users/Vaughan/xxx/protocol/xxx-protobufjs/node_modules/flowgen"
    err: 
      name: "Error"
      message: "ENOENT: no such file or directory, lstat '/Users/Vaughan/xxx/packages/xxx/protocol/xxx-protobufjs/node_modules/flowgen'"
      code: "ENOENT"
      stack: "Error: ENOENT: no such file or directory, lstat '/Users/Vaughan/xxx/packages/xxx/protocol/xxx-protobufjs/node_modules/flowgen'"
```

When I look in `node_modules` it is empty.

2nd time I ran it, it works. Looks like some kind of race condition.
