### ISSUE TITLE
Request: Preserve comments and key orders in `package.yaml`/`pnpm-workspace.yaml` when run 'pnpm install --save', 'pnpm update --latest', etc.

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#2008]
## Problem

One of the advantages of format such as YAML and JSON5 is that it supports comments. Commands that modifies these files render these comments pointless.

For example, this `package.yaml`:

```yaml
dependencies:

  # the following dependencies are required to do something
  foo: 0.1.2
  bar: 1.2.3

  # the following dependencies are others' peer
  abc: 2.3.4 # peer dependency of foo
  def: 3.4.5 # peer dependency of bar
```

will be turn into this:

```yaml
dependencies:
  abc: 2.3.4
  bar: 1.2.3
  def: 3.4.5
  foo: 0.1.2
```

### 1. Attempt on a subset of YAML first

YAML is a complicated format, as such, it is understandable to use libraries such as `js-yaml` to write a YAML files. However, most of the time, YAML that users write is rather simple: No leading indent before `dependencies` and `devDependencies` field, one level of indent before each dependency name. For this reason, one can remove/insert lines with correct indentation in between YAML content and get the desired result.

**Possible strategy:**

1. Check if the YAML string satisfies a strict subset (such as No JSON block).
2. If it satisfies, treat YAML like a list of lines.
3. If it doesn't, and if user allows it, use YAML library to deserialize object.

### 2. Do not edit YAML file by default

pnpm may choose to ignore `package.yaml` file and print a warning, or pnpm may emit an error, depends on the command.

### 3. New command-line flags

When YAML file satisfies the subset
* `pnpm install --append-yaml-lines`: Add new lines to the end of dependencies/devDependencies list.
* `pnpm install --prepend-yaml-lines`: Add new lines to the beginning of dependencies/devDependencies list.
* `pnpm install --under-yaml-comment [number|string]`: Add new lines to under a comment block.

When YAML file does not satisfy the subset:
* `pnpm <command> --[no-]force-dump-yaml`: Whether to use YAML library to dump YAML content.

## This may also apply to JSON5

JSON5 has the following features: Comments, trailing commas, etc.
