### ISSUE TITLE
pnpm install sometimes produces invalid tarball urls

### ISSUE THREAD

**Issue by calvin-uc** [pnpm/pnpm#2152]
I'm encountering an issue with `pnpm install`. Locally everything installs as expected, but when installing in a remote environment such as circleci (with a `pnpm-lock.yaml`) there's an error of
`ERROR  404 Not Found: https://<hostname>/@uc/corp-nav/-/@uc/corp-nav-2.8.0.tgz`

Originally the tarball path is: `/@uc/corp-nav/-/@uc/corp-nav-2.8.0.tgz`

I removed the `pnpm-lock.yaml` and `node_modules` and ran `pnpm install` again to find that the tarball is now: `https://<hostname>/@uc/corp-nav/-/@uc/corp-nav-2.8.0.tgz` in a few packges.

After removing the `pnpm-lock.yaml` once more and running `pnpm install` again the tarballs in more packages are now `https://<hostname>/@uc/corp-nav/-/@uc/corp-nav-2.8.0.tgz`.

I'm not sure how the same `pnpm install` generates different a `pnpm-lock.yaml` files.

### Code to reproduce the issue:

```shell
$ pnpm install
```

### Expected behavior:

Consisent `pnpm-lock.yaml` file.

### Actual behavior:

original `pnpm-lock.yaml`
```yaml
/@uc/corp-nav/2.8.0:
    ...
    resolution:
      integrity: sha1-wnW6QNxnoTOZ0hMRJV4MWe+Cz0s=
      tarball: /@uc/corp-nav/-/@uc/corp-nav-2.8.0.tgz
```

after clearing `node_modules`
```yaml
  /@uc/corp-nav/2.8.0:
    ...
    resolution:
      integrity: sha1-wnW6QNxnoTOZ0hMRJV4MWe+Cz0s=
      tarball: 'https://<hostname>/@uc/corp-nav/-/@uc/corp-nav-2.8.0.tgz'
```

### Additional information:

 - `node -v` prints: v10.11.0
 - Operating System: Debian GNU/Linux 8 (jessie)
