### ISSUE TITLE
A rare instance of failure of pnpm self installer in Travis CI

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#2244]
[saved log from Travis CI (use cat or curl in terminal to see color)](https://gist.github.com/KSXGitHub/327df7c2a212c1f8399dfc6833c6605c)

**.travis.yml**

```yaml
branches:
  except:
    - draft
    - tmp
    - /.*\.(draft|tmp)$/
    - /^(draft|tmp)\..*/

language: node_js

node_js:
  - '12.11.0'
  - '13'

cache:
  directories:
    - $HOME/.pnpm-store
    - $HOME/.node-gyp
    - $HOME/.node_libraries

before_cache:
  - pnpm store prune

before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm --version
  - bash ci/before-install.sh

install:
  - pnpm recursive install
  - bash ci/install.sh

script:
  - pnpm run test:ci
  - pnpm run build

after_script:
  - bash ci/after-script.sh

env:
  - SHOW_SPAWN_CMD=true
```

![Screenshot of Build Logs](https://user-images.githubusercontent.com/11488886/71654815-4d004980-2d66-11ea-8551-2d93787eab5d.png)

---

[And it still fails](https://travis-ci.org/KSXGitHub/personal-packages/jobs/631767262)
