### ISSUE TITLE
Add GitHub to CI docs

### ISSUE THREAD

**Issue by jamesarosen** [pnpm/pnpm#2672]
The [Continuous Integration docs](https://pnpm.js.org/en/continuous-integration) have instructions for using `pnpm` with Travis, Semaphore, AppVeyor, and Sail CI.

pnpm/pnpm itself uses GitHub actions and [installs](https://github.com/pnpm/pnpm/blob/69fd42440cd1c11d1dd4bbf41769e4725e128a87/.github/workflows/node-windows.yml#L29-L32) pnpm with
```yml
- name: install pnpm
  run: |
    npm install pnpm@next -g
    pnpm --version
```
Is that the recommended technique for other projects? Do you recommend `pnpm@next` or is that special because it's the project testing itself?
