### ISSUE TITLE
Root dev dependency causes unexpected peer dependency

### ISSUE THREAD

**Issue by walkerburgin** [pnpm/pnpm#2983]
### Code to reproduce the issue:
I don't have a concise repro yet and I haven't had any luck with the things I've tried so far.

### Expected behavior:
I'm actually not sure if this is a bug, but the behavior was surprising to me and I'm not sure how to explain it. 

We have an internal package in the vein of `react-scripts` which encapsulates a lot of our build tooling. That package currently has a dependency on `typescript@~4.0.5` (it actually depends on a package which depends on `typescript@~4.0.5` if that matters). But in any case, it's a dependency not a peer dependency. We take a dependency on this build scripts package from the root of our monorepo to make the build tooling easier to update since we update it frequently. This afternoon we added a dev dependency on TypeScript to the root of the monorepo, and the lockfile entry looked like this: 

```yaml
importers:
  .:
    devDependencies:
      'internal-build-scripts': 1.0.0_typescript@4.0.5    # <-- why is typescript being treated as a peer dependency?
  # ...
packages:
  /internal-build-scripts/1.0.0_typescript@4.0.5:
    dependencies:
      # ...
    dev: true
    hasBin: true
    peerDependencies:
      typescript: '*'
```

The thing that's confusing me is that typescript is **not** a peer dependency of internal-build-scripts, but for some reason it started being treated as one as soon as we added `typescript` to the root of the monorepo. I would have expected the lockfile to look like this: 

```yaml
importers:
  .:
    devDependencies:
      'internal-build-scripts': 1.0.0
  # ...
packages:
  /internal-build-scripts/1.0.0:
    dependencies:
      # ...
    dev: true
    hasBin: true
```

This isn't really hurting anything in our setup at the moment, but it caught me off guard. Any idea what might be going on? Is this some edge case that I don't understand? I would believe that this is deliberate and that I just don't understand why. 

### Actual behavior:
PNPM adds typescript as a peer dependency unexpectedly. 

### Additional information:

 - `node -v` prints: v10.23.0
 - Windows, macOS, or Linux?: Mac
