### ISSUE TITLE
Github Action Releases fail with Cannot install with "frozen-lockfile"

### ISSUE THREAD

**Issue by DavidWells** [pnpm/pnpm#3664]
### pnpm version:

pnpm 6.10.0

### Code to reproduce the issue:

This PR https://github.com/DavidWells/pnpm-workspaces-example/pull/13/files came from this job https://github.com/DavidWells/pnpm-workspaces-example/actions/runs/1122473540

When merging this PR this resulting action errors out with 

```
Scope: all 6 workspace projects
Lockfile is up-to-date, resolution step is skipped
 ERROR  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up-to-date with src/app/package.json
Error: Process completed with exit code 1.
```

https://github.com/DavidWells/pnpm-workspaces-example/runs/3307725114?check_suite_focus=true#step:7:9

These are run via this workflow https://github.com/DavidWells/pnpm-workspaces-example/blob/master/.github/workflows/changeset-version.yml#L41

### Expected behavior:

I'm hoping this will just work. The only way I could side step this issue is by providing `--frozen-lockfile false` flag but this seems like it ignores the cache everytime. 

I've tried to run `pnpm install` after `pnpx changeset` here https://github.com/DavidWells/pnpm-workspaces-example/blob/master/package.json#L32 but it also fails with the lockfile message.

Any pointers on how to properly set this up would be very helpful 

### Actual behavior:

Fails

### Additional information:

 - `node -v` prints: 16+
 - Windows, macOS, or Linux?: ubuntu github action
 
 Related? https://github.com/pnpm/pnpm/issues/2807

**Comment by zkochan** [comment]
After changeset updates the versions, `pnpm install` should be executed to update the lockfile. In CI environments, frozen-lockfile is on by default, so in the workflow, run `pnpm install --no-frozen-lockfile` after running changeset and commit the update lockfile.

**Comment by bestickley** [comment]
For reference, I had to add `pnpm install --no-frozen-lockfile && git add .` before the `version` command as noted above, otherwise I got an error:
```
{
      resource: 'PullRequest',
      code: 'custom',
      message: 'No commits between main and changeset-release/main'
    }
```

publish.yml
```yaml
name: Publish

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [./.github/workflows/publish.yml, packages/**]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Install PNPM
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install dependencies
        # https://github.com/pnpm/pnpm/issues/3664
        run: pnpm install --no-frozen-lockfile && git add .

      - name: Compile TypeScript
        run: pnpm build

      # This step will create or update the PR, "Package Versions". When that
      # PR is merged, it will release to NPM. Maintainers should ensure PR is
      # passing all checks before merging PR since audit, lint, test doesn't run
      # in this workflow
      - name: Create PR, Update PR, or Release to NPM
        uses: changesets/action@v1
        with:
          # publish command will only run upon merge of PR created by changesets.
          # publish doesn't run on every push to main
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
