### ISSUE TITLE
pnpm import does not respect nested yarn.lock

### ISSUE THREAD

**Issue by tgroutars** [pnpm/pnpm#4385]
### Code to reproduce the issue:

Super minimal repro [here](https://github.com/tgroutars/pnpm-import-repro)

### Expected behavior:

When running pnpm import in a workspace, pnpm should take the nested `yarn.lock`s into account. 
In the repro above, I have lodash installed in the root and in a nested package

The lockfile in the root looks like this:
```
lodash@^4.17.5:
  version "4.17.5"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.5.tgz#99a92d65c0272debe8c96b6057bc8fbfa3bed511"
  integrity sha512-svL3uiZf1RwhH+cWrfZn3A4+U58wbP0tGVTLQPbjplZxZ8ROD9VLuNgsRniTlLe7OlSqR79RUehXgpBW/s0IQw==
```

The lockfile in the nested package looks like this
```
lodash@^4.17.15:
  version "4.17.15"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.15.tgz#b447f6670a0455bbfeedd11392eff330ea097548"
  integrity sha512-8xOcRHvCjnocdS5cpwXQXVzmmh5e5+saE2QGoeQmbKmRS6J3VQppPOIt0MnmE+4xlZoumy0GPG0D0MVIQbNA1A==
```

When running pnpm, I expect `pnpm-lock.yaml` to have this in the `importers`

```yaml
  .:
    specifiers:
      lodash: ^4.17.5
    dependencies:
      lodash: 4.17.5

  packages/components:
    specifiers:
      lodash: ^4.17.15
    dependencies:
      lodash: 4.17.15
```

### Actual behavior:

The actual behavior is that the locked version of lodash is not respected for my nested package, and still installs the latest version accepted by my `package.json`. Notice that lodash `4.17.21` is installed instead of `4.17.15` like `yarn.lock` specifies. It does work as expected for the root, but not for nested packages

```yaml
  .:
    specifiers:
      lodash: ^4.17.5
    dependencies:
      lodash: 4.17.5

  packages/components:
    specifiers:
      lodash: ^4.17.15
    dependencies:
      lodash: 4.17.21
```

### Additional information:

 - `node -v` prints: v14.17.3
 - Windows, macOS, or Linux?: macOS
