### ISSUE TITLE
`pnpm ls` not detecting changes to package's `dependencies` resolutions

### ISSUE THREAD

**Issue by maschwenk** [pnpm/pnpm#4420]
### pnpm version:

`6.34.0`

### Code to reproduce the issue:

With a `pnpm-lock.yaml` like so:
```
apps/app_name:
    specifiers:
      dotenv: ^8.2.0
    dependencies:
      dotenv: 8.2.0
```
If we manually change the resolved `dotenv` version to something different that still satisfies the specifier, e.g. 

```
apps/app_name:
    specifiers:
      dotenv: ^8.2.0
    dependencies:
      dotenv: 8.3.0
```

```
pnpm ls --json --depth 0 --filter="...[origin/master]" | jq 'map(.name)'
```

does not consider `apps/app_name` as changed, which means that potentially we could miss out running tests against this change.

### Expected behavior:

`pnpm ls` would show changes to resolved `dependencies` as changes to the owning package.

### Actual behavior:

`pnpm ls` only shows the root package as changed (because the `pnpm-lock.yaml` has changed).

### Additional information:

 - `node -v` prints: `v16.13.1`
 - Windows, macOS, or Linux?: `macOS`
