### ISSUE TITLE
Investigate grouping specifier and version fields by dependency name in pnpm-lock.yaml importers section to reduce merge conflicts

### ISSUE THREAD

**Issue by gluxon** [pnpm/pnpm#4725]
See context in https://github.com/pnpm/rfcs/pull/1#discussion_r838996282. Filing an issue and assigning myself for personal tracking.

## Before

```yaml
# pnpm-lock.yaml
importers:

  project:
    specifiers:
      react: ^1.0.0
      react-dom: ^1.0.0
    dependencies:
      react: 1.0.0
      react-dom: 1.0.0_react-dom@1.0.0
```

## After

```yaml
# pnpm-lock.yml
importers:
  project:
    dependencies:

      react:
        specifier: ^1.0.0
        version: 1.0.0_react-dom@1.0.0

      react-dom:
        specifier: ^1.0.0
        version: 1.0.0
```

The first version of this will be hidden behind a feature flag and limited to the `PnpmLockfile` serialization/deserialization stages.
