### ISSUE TITLE
pnpm publish doesn't work with npm access token

### ISSUE THREAD

**Issue by cundejo** [pnpm/pnpm#4937]
In our company, we deploy private libraries that we have in a monorepo to the npm registry.

### Code to reproduce the issue:
 To deploy new versions we use this job in GitLab.
  
```yaml
default:
  image: node:12.22.5

before_script:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@latest-6
  - pnpm config set store-dir .pnpm-store
  - pnpm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}

stages:
  - deploy

npm-publish:
  stage: deploy
  script:
    - pnpm -r install --aggregate-output
    - pnpm -r publish --no-git-checks
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  only:
      - master
```

### Expected behavior:
CI pipeline should publish correctly all the libraries with new versions.

### Actual behavior:
The pipeline fails asking for OTP:
(Included only the error)
```bash
$ pnpm -r publish --no-git-checks
....
npm ERR! code EOTP
npm ERR! This operation requires a one-time password from your authenticator.
npm ERR! You can provide a one-time password by passing --otp=<code> to the command you ran.
npm ERR! If you already provided a one-time password then it is likely that you either typoed
npm ERR! it, or it timed out. Please try again.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-26T21_27_11_550Z-debug.log
```

To clarify, we are sure the `NPM_TOKEN` is correct and works because we can publish with `lerna publish` using the token.

### Additional information:

 - `node -v` prints: 12.22.5
 - Windows, macOS, or Linux?: Linux/CI

**Comment by zkochan** [comment]
pnpm actually runs npm for publish. I think you need to generate an auth token for CI (that doesn't require OTP). I don't know how lerna is able to omit OTP.

**Comment by cundejo** [comment]
@zkochan the auth token was generated in npm correctly, added to CI variables, and included in the env: 

```bash
pnpm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
```

And works perfectly as I said before because we are using it to publish with lerna right now.

**Comment by TheUnlocked** [comment]
I'm experiencing this as well. `npm publish` works fine, `pnpm publish` errors out with:

```
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://registry.npmjs.org/
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

**Comment by zyyv** [comment]
> I'm experiencing this as well. `npm publish` works fine, `pnpm publish` errors out with:
> 
> ```
> npm ERR! code ENEEDAUTH
> npm ERR! need auth This command requires you to be logged in to https://registry.npmjs.org/
> npm ERR! need auth You need to authorize this machine using `npm adduser`
> ```

Hi. same issue in github actions with monorepo. And have you resolve it? can someone guide me?

**Comment by hrigner** [comment]
Hey! 👋 
I have the same issue, `npm publish` works fine but `pnpm publish` is failing with 
```
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://registry.npmjs.org/
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

**Comment by adamlarsonlee** [comment]
I am able to publish just fine locally using `npm config set` with my auth token, however in CICD I'm failing with the same error. This is how I add the auth token in the job script:

```yml
- echo "//${CI_SERVER_HOST}/api/v4/projects/${CHIEF_PACKAGE_REGISTRY_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
```

**Comment by tomimarkus991** [comment]
How should i publish?

npm publish --no-git-checks nor pnpm publish --no-git-checks works

**Comment by navaru** [comment]
The version 7.28 doesn't work, but the 7.27.1 works fine. Here's the relevant part of the config to make it work:

```yaml
publish:
  stage: publish
  before_script:
    - corepack enable
    - corepack prepare pnpm@7.27.1 --activate
    - pnpm config set "//${GITLAB_REGISTRY}:_authToken=${CI_JOB_TOKEN}"
```

**Comment by semiautomatix** [comment]
> 

I'm still struggling, using the below:

```yaml
image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm config set "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}"
  script:
    - pnpm install --frozen-lockfile --strict-peer-dependencies
    # - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    # No Git checks if the pipeline alters the local branch
    - pnpm publish --publish-branch main --no-git-checks
```
Error:
```bash
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://gitlab.com/api/v4/projects/43729055/packages/npm/
npm ERR! need auth You need to authorize this machine using `npm adduser`
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-07T12_23_23_743Z-debug-0.log
```

Any suggestions?

**Comment by zkochan** [comment]
@semiautomatix your issue is not related to this issue. For now use `npm config set` for setting the auth token

and track https://github.com/pnpm/pnpm/issues/6181

**Comment by semiautomatix** [comment]
> @semiautomatix your issue is not related to this issue. For now use `npm config set` for setting the auth token
> 
> and track #6181

I'm met with the same result using `npm config set` or echoing to the file.

`npm publish` works as intended.

**Comment by semiautomatix** [comment]
gitlab-ci.yml

```yaml
image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - npm config set "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}"
  script:
    - pnpm install --frozen-lockfile --strict-peer-dependencies
    - pnpm publish --publish-branch main --no-git-checks
```

I thought I'd double-check this doesn't work. No luck, I'm afraid.

```
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://gitlab.com/api/v4/projects/43729055/packages/npm/
npm ERR! need auth You need to authorize this machine using `npm adduser`
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-08T00_50_37_922Z-debug-0.log
```

**Comment by andskre** [comment]
Here is my working GH action for publishing:

```yaml
name: 🚀 Publish

on:
  release:
    types: [created]

jobs:
  publish-github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com/

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: 📝 Version
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: pnpm version ${TAG_NAME} --no-git-tag-version

      - name: 🐙 Publish no GitHub
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm publish --no-git-checks
```

But pls keep your attention on the `registry-url` - you need a trailing slash on the end of the registry URL. Don't ask me how I know it, but if you would ask [here](https://stackoverflow.com/questions/57279087/authentication-error-on-publishing-to-private-npm-repository-on-nexus) you'll find the answer 😅
