### ISSUE TITLE
Non-deterministic install

### ISSUE THREAD

**Issue by JanJakes** [pnpm/pnpm#5106]
I discovered a case where `pnpm install` doesn't behave deterministically — when being run again and again, a package (`promise-inflight`) is sometimes added and sometimes removed, resulting in changes in `pnpm-lock.yaml`.

I'm linking [a repository](https://github.com/JanJakes/pnpm-nondeterministic-install) with the issue reproduction. Note that there are many missing peer deps as I was trying to cut down the dependencies and still reproduce the issue.

### pnpm version:
7.6.0

### Code to reproduce the issue:
https://github.com/JanJakes/pnpm-nondeterministic-install

### Expected behavior:
No matter how many times I run `pnpm install` consecutively, there should be no changes in `pnpm-lock.yaml` and `node_modules`.

### Actual behavior:
When `pnpm install` is being run repeatedly, a package keeps being randomly added and removed.

### Additional information:
All details are in the readme of the issue reproduction: https://github.com/JanJakes/pnpm-nondeterministic-install

**Comment by gluxon** [comment]
Hi @JanJakes, are you using JFrog Artifactory by any chance? I think this is an instance of https://github.com/pnpm/pnpm/issues/5004 if so.

See https://www.jfrog.com/jira/browse/RTFACT-27265 for the Artifactory issue.

**Comment by JanJakes** [comment]
Hi @gluxon, I don't know what JFrog Artifactory is 😄 But no, I'm not using it. See the reproduction repo and the README in there — it's really all that's needed to reproduce the issue so I don't think it's related to the thread you've linked.

**Comment by gluxon** [comment]
Thanks for checking @JanJakes. That is interesting. I'm realizing you do have a different issue since the existing reference to `promise-inflight` has `peerDependenciesMeta`.

https://github.com/JanJakes/pnpm-nondeterministic-install/blob/bac7f2c8b3e69af6841bb5bab5c19882f8ef686c/pnpm-lock.yaml#L7854-L7861

As far as I can tell, adding the `_bluebird@3.7.2` peers suffix to `promise-inflight` is correct. Surprised there's instances where pnpm won't see that peer dependency.

```
  /cacache/12.0.4:
    resolution: {integrity: sha512-a0tMB40oefvuInr4Cwb3GerbL9xTj1D5yg0T5xrjGCGyfvbxseIXX7BAO/u/hIXdafzOI5JC3wDwHyf24buOAQ==}
    dependencies:
      bluebird: 3.7.2
      chownr: 1.1.4
      figgy-pudding: 3.5.2
      glob: 7.2.3
      graceful-fs: 4.2.9
      infer-owner: 1.0.4
      lru-cache: 5.1.1
      mississippi: 3.0.0
      mkdirp: 0.5.5
      move-concurrently: 1.0.1
      promise-inflight: 1.0.1
      rimraf: 2.7.1
      ssri: 6.0.2
      unique-filename: 1.1.1
      y18n: 4.0.3
    dev: true
```

I'll let the maintainers comment. Thanks for creating such a great repro.

**Comment by JanJakes** [comment]
@gluxon Thanks for looking into it! I guess saying that `promise-inflight` keeps being added and removed was not exact — maybe it's more like it keeps being added with and without the `bluebird` part:

<img width="1033" alt="181184226-57174c22-ace8-4e4a-bda8-ff21a2e607fd" src="https://user-images.githubusercontent.com/141436/181440907-a5e69953-f080-4592-ab6b-ce9c20bbdb06.png">

I was trying to cut down the deps as much as possible (we have much more than in the repro) but at some point it seems that it no longer happens when I remove even more than in the repro. Running `pnpm why promise-inflight` reveals that many subdependencies require it.

The lockfile in this state is probably important. Deleting it and installing the packages again may result in a different (and stable) install.

As a side note, it seems that ussing the rolling range (`"workspace-1": "workspace:^"`) in workspace 2 causes `pnpm` to always resolve something, instead of skipping that step when nothing changed.

**Comment by JanJakes** [comment]
I forgot to mention that the lockfile was generated using `pnpm import` from `package-lock.json`. Neverthless, it's a valid lockfile and the non-determinism seems to be there.

**Comment by apaniel** [comment]
I have the same issue with promise-inflight and blueBird, when I run a pnpm install it sometimes changes

**Comment by gluxon** [comment]
I noticed that [JanJakes/pnpm-nondeterministic-install](https://github.com/JanJakes/pnpm-nondeterministic-install) no longer reproduces after v7.9.0. It does reproduce on v7.8.0. A `git bisect` between these 2 versions narrowed it down to: 0321ca32a4d5cb858a53f519dff677f04ea174de

The removal of parallelism there probably made this repro more deterministic, but I think the problem still exists in general. I've seen it on 7.13.5 in one of my repos.

@apaniel What version of pnpm do you see the problem on?

**Comment by apaniel** [comment]
@gluxon I can reproduce in latest 7.27.0

**Comment by gluxon** [comment]
Haven't nailed down exactly what's happening but getting close. Adding some debugging notes for myself.

## Theory

The `promise-inflight` peer dependency on `bluebird` comes from the Yarn compatibility database. [`yarnpkg-extensions/sources/index.ts#`](https://github.com/yarnpkg/berry/blob/9b3f92b88753d58a12bf1aac637b2c4fcb62f4a8/packages/yarnpkg-extensions/sources/index.ts#L116-L121).

```ts
{
  [`promise-inflight@*`, {
    peerDependenciesMeta: {
      [`bluebird`]: optionalPeerDep,
    },
  }],
}
```

I'm guessing there are cases where `cacache` is resolved without the incompatibility patches to `promise-inflight`.

## Logging

Logging `{ nodeId, node }` in `resolvePeersOfNode` here.

https://github.com/pnpm/pnpm/blob/761be978b2ed70a5337eaab14e13dab103a6cf93/packages/resolve-dependencies/src/resolvePeers.ts#L188

### Correct (`inflight-promise` has peer dep)

```yaml
{
  nodeId: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>',
  node: {
    children: {
      bluebird: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/bluebird/3.7.2>',
      chownr: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/chownr/1.1.4>',
      'figgy-pudding': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/figgy-pudding/3.5.2>',
      glob: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/glob/7.2.3>',
      'graceful-fs': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/graceful-fs/4.2.9>',
      'infer-owner': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/infer-owner/1.0.4>',
      'lru-cache': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/lru-cache/5.1.1>',
      mississippi: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/mississippi/3.0.0>',
      mkdirp: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/mkdirp/0.5.5>',
      'move-concurrently': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/move-concurrently/1.0.1>',
      'promise-inflight': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/promise-inflight/1.0.1>',
      rimraf: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/rimraf/2.7.1>',
      ssri: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/ssri/6.0.2>',
      'unique-filename': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/unique-filename/1.1.1>',
      y18n: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/y18n/4.0.3>'
    },
    depth: 4,
    installable: true,
    resolvedPackage: {
      additionalInfo: [Object],
      depPath: '/cacache/12.0.4',
      dev: false,
      fetchingBundledManifest: [AsyncFunction (anonymous)],
      fetchingFiles: [AsyncFunction (anonymous)],
      filesIndexFile: '/Users/gluxon/Library/pnpm/store/v3/files/6b/4b4c078d2879fbee227af80b06f719eadb2fdc538f50f9ca0d13e71ae31821b27ef6f1b1e2175fb0403bfbbf8485dd69fcce239242df00f01f27f6e1bb8e01-index.json',
      finishing: [AsyncFunction (anonymous)],
      hasBin: false,
      hasBundledDependencies: false,
      id: 'registry.npmjs.org/cacache/12.0.4',
      name: 'cacache',
      optional: false,
      optionalDependencies: Set(0) {},
      patchFile: undefined,
      peerDependencies: {},
      peerDependenciesMeta: undefined,
      prepare: false,
      prod: true,
      requiresBuild: false,
      resolution: [Object],
      version: '12.0.4'
    }
  }
}
```

### Incorrect (`inflight-promise` is missing peer dep)

```yaml
{
  nodeId: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>',
  node: {
    children: {
      bluebird: 'registry.npmjs.org/bluebird/3.7.2',
      chownr: 'registry.npmjs.org/chownr/1.1.4',
      'figgy-pudding': 'registry.npmjs.org/figgy-pudding/3.5.2',
      glob: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/glob/7.2.3>',
      'graceful-fs': 'registry.npmjs.org/graceful-fs/4.2.9',
      'infer-owner': 'registry.npmjs.org/infer-owner/1.0.4',
      'lru-cache': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/lru-cache/5.1.1>',
      mississippi: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/mississippi/3.0.0>',
      mkdirp: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/mkdirp/0.5.5>',
      'move-concurrently': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/move-concurrently/1.0.1>',
      'promise-inflight': 'registry.npmjs.org/promise-inflight/1.0.1',
      rimraf: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/rimraf/2.7.1>',
      ssri: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/ssri/6.0.2>',
      'unique-filename': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/unique-filename/1.1.1>',
      y18n: 'registry.npmjs.org/y18n/4.0.3'
    },
    depth: 4,
    installable: true,
    resolvedPackage: {
      additionalInfo: [Object],
      depPath: '/cacache/12.0.4',
      dev: false,
      fetchingBundledManifest: [AsyncFunction (anonymous)],
      fetchingFiles: [AsyncFunction (anonymous)],
      filesIndexFile: '/Users/gluxon/Library/pnpm/store/v3/files/6b/4b4c078d2879fbee227af80b06f719eadb2fdc538f50f9ca0d13e71ae31821b27ef6f1b1e2175fb0403bfbbf8485dd69fcce239242df00f01f27f6e1bb8e01-index.json',
      finishing: [AsyncFunction (anonymous)],
      hasBin: false,
      hasBundledDependencies: false,
      id: 'registry.npmjs.org/cacache/12.0.4',
      name: 'cacache',
      optional: false,
      optionalDependencies: Set(0) {},
      patchFile: undefined,
      peerDependencies: {},
      peerDependenciesMeta: undefined,
      prepare: false,
      prod: true,
      requiresBuild: false,
      resolution: [Object],
      version: '12.0.4'
    }
  }
}
```

### Diff
```diff
diff --git a/incorrect.yml b/correct.yml
index 8dfacce..de0234a 100644
--- a/incorrect.yml
+++ b/correct.yml
@@ -2,21 +2,21 @@
   nodeId: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>',
   node: {
     children: {
-      bluebird: 'registry.npmjs.org/bluebird/3.7.2',
-      chownr: 'registry.npmjs.org/chownr/1.1.4',
-      'figgy-pudding': 'registry.npmjs.org/figgy-pudding/3.5.2',
+      bluebird: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/bluebird/3.7.2>',
+      chownr: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/chownr/1.1.4>',
+      'figgy-pudding': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/figgy-pudding/3.5.2>',
       glob: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/glob/7.2.3>',
-      'graceful-fs': 'registry.npmjs.org/graceful-fs/4.2.9',
-      'infer-owner': 'registry.npmjs.org/infer-owner/1.0.4',
+      'graceful-fs': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/graceful-fs/4.2.9>',
+      'infer-owner': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/infer-owner/1.0.4>',
       'lru-cache': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/lru-cache/5.1.1>',
       mississippi: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/mississippi/3.0.0>',
       mkdirp: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/mkdirp/0.5.5>',
       'move-concurrently': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/move-concurrently/1.0.1>',
-      'promise-inflight': 'registry.npmjs.org/promise-inflight/1.0.1',
+      'promise-inflight': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/promise-inflight/1.0.1>',
       rimraf: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/rimraf/2.7.1>',
       ssri: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/ssri/6.0.2>',
       'unique-filename': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/unique-filename/1.1.1>',
-      y18n: 'registry.npmjs.org/y18n/4.0.3'
+      y18n: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/y18n/4.0.3>'
     },
     depth: 4,
     installable: true,
```

I think the important line is:

```diff
-      'promise-inflight': 'registry.npmjs.org/promise-inflight/1.0.1',
+      'promise-inflight': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/promise-inflight/1.0.1>',
```
