### ISSUE TITLE
circular links of peer dependencies on Windows can cause backslashes to appear in pnpm-lock file

### ISSUE THREAD

**Issue by trasich** [pnpm/pnpm#5324]
### pnpm version:

>\>=7.9.2

### Code to reproduce the issue:
Windows only.
monorepo  with a following structure
..
|-apps
|   |-App@0.1.0
|-packages
   | - packA@0.1.0 

`pnpm-workspace.yaml`
```yml
packages:
  - apps/*
  - packages/*
```

another repository with a following structure
..
|-packB@0.1.0

packB has peerDependency to packA@^0.1.0
App has dependency to packA (workspace:*)
App has dependency to packB@^0.1.0

### Expected behavior:

pnpm-lock.yml to contain 
```yml
packages:
   /packB/0.1.0_hash:
     peerDependencies:
       'packA':^0.1.0
     dependencies:
       'packA':link:packages/packA
```
### Actual behavior:

pnpm-lock.yml contains
```yml
packages:
   /packB/0.1.0_hash:
     peerDependencies:
       'packA':^0.1.0
     dependencies:
       'packA':link:packages\packA
```
### Additional information:

 - `node -v` prints: v16.15.1
 - Windows, macOS, or Linux?: Windows only
