### ISSUE TITLE
`--use-node-version` fails when it contains version outside support (only GitHub Action)

### ISSUE THREAD

**Issue by privatenumber** [pnpm/pnpm#5516]
### Code to reproduce the issue:
GitHub Action workflow:
https://github.com/privatenumber/manten/blob/node-v12/.github/workflows/test.yml#L32

Minimal example:
```yaml
name: Test

on:
  push:
    branches: [develop]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
        run_install: true

    - name: Test
      run: pnpm run --use-node-version=12.22.12 test

```

GitHub Action logs:
https://github.com/privatenumber/manten/actions/runs/3275341634/jobs/5390061823

### Expected behavior:
For pnpm to run the `test` script with the Node.js version passed in. This is expected because it works fine locally on macOS, but not on the GitHub Actions CI.

### Actual behavior:
It seems like pnpm tries to run using the Node.js version passed in:

```
ERROR: This version of pnpm requires at least Node.js v14.6
The current version of Node.js is v12.22.12
Visit https://r.pnpm.io/comp to see the list of past pnpm versions with respective Node.js version support.
```

However, this is unexpected because it works locally on the same pnpm version.

Guessing this might be fixed by https://github.com/pnpm/action-setup/pull/31, but also wondering if pnpm could just start with the default Node.js and spawn the child process with the specified version.

### Additional information:

 - `node -v` prints: v16.17.0
 - Windows, macOS, or Linux?: Linux (GitHub Action)
