### ISSUE TITLE
preserve comments in package yaml

### ISSUE THREAD

**Issue by mptr** [pnpm/pnpm#5595]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

It would be nice, if pnpm preserves comments placed in a package.yaml file.

## Current behavior

package.yaml (pre install)
```yaml
...
scripts:
  # just a test
  foo: echo bar
dependencies:
  ...
```

run `pnpm install <dep>`

package.yaml (post install)
```yaml
...
scripts:
  foo: echo bar
dependencies:
  <dep>: <version>
  ...
```

## Desired behavior

package.yaml (pre install)
```yaml
...
scripts:
  # just a test
  foo: echo bar
dependencies:
  ...
```

run `pnpm install <dep>`

package.yaml (post install)
```yaml
...
scripts:
  # just a test
  foo: echo bar
dependencies:
  <dep>: <version>
  ...
```
