### ISSUE TITLE
Invalid format for "pnpm store path" when NPM token is missing 

### ISSUE THREAD

**Issue by nglgzz** [pnpm/pnpm#5635]
### Code to reproduce the issue:

Create a repo containing an .npmrc file with: 

```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
```

And a GitHub action that installs and caches dependencies using the configuration described here: https://github.com/pnpm/action-setup/blob/master/README.md#use-cache-to-reduce-installation-time

```yaml
    - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        
```

### Expected behavior:

The steps mentioned above should pass fine.

### Actual behavior:

The first step fails with:
```
Error: Unable to process file command 'output' successfully.
Error: Invalid format ' WARN  Issue while reading "/home/runner/work/[redacted]/.npmrc". Failed to replace env in config: ${NPM_TOKEN}'
```

### Additional information:

 - `node -v` prints: v18.12.0
 - Windows, macOS, or Linux?: github actions (running on `ubuntu-latest`)

I understand that passing the environment variable for the token would get rid of this error, but that is a workaround, not a solution. The `pnpm store path` command works correctly without the token, so I should be able to parse its output without the token. I cannot do this though, because the warnings are logged to STDOUT.

In practice, this means that if I run the command in the snipped below (redirecting STDERR to ignore the warnings), the warnings are still there, when instead I would expect to only get the path.
```
$ pnpm store path 2> /dev/null
 WARN  Issue while reading "/home/nglgzz/projects/[redacted]/.npmrc". Failed to replace env in config: ${NPM_TOKEN}
 WARN  Issue while reading "/home/nglgzz/projects/[redacted]/.npmrc". Failed to replace env in config: ${NPM_TOKEN}
/home/nglgzz/.local/share/pnpm/store/v3
```
