### ISSUE TITLE
pnpm@7.17.0 generate different lockfile in CI and localy

### ISSUE THREAD

**Issue by mysteryven** [pnpm/pnpm#5691]
### pnpm version: 

7.17.0

### Code to reproduce the issue:

https://github.com/mysteryven/umi/pull/1/commits/cec692ce24cfd2bab2b166c76883d4564fa3e621

I used pnpm@7.3.0 previously, and want to update to pnpm@7.17.0, This is my change in `package.json`:

```diff
- "packageManager": "pnpm@7.3.0",
+ "packageManager": "pnpm@7.17.0",
```

Then, I run `pnpm i` to update my lockfile locally, and push it to remote. But this time CI and Local generated different lock file with same version pnpm .

For `@umijs/renderer-vue`, [its dependencies](https://github.com/mysteryven/umi/blob/d5952db4372213375c567c762c59175b25c89019/packages/renderer-vue/package.json#L23) are as below: 

```json
  "dependencies": {
    "@babel/runtime": "7.18.9"
  },
  "peerDependencies": {
    "vue": ">=3.2.31",
    "vue-router": ">=4.0.12"
  },
```

CI will be, it is same with pnpm@7.3.0 : 

```yaml
  packages/renderer-vue:
    specifiers:
      '@babel/runtime': 7.18.9
    dependencies:
      '@babel/runtime': 7.18.9
```

But Local will be:

```yaml
  packages/renderer-vue:
    specifiers:
      '@babel/runtime': 7.18.9
      vue: '>=3.2.31'
      vue-router: '>=4.0.12'
    dependencies:
      '@babel/runtime': 7.18.9
      vue: 3.2.36
      vue-router: 4.0.15_vue@3.2.36
```

### Expected behavior:

Install dependencies successfully.

### Actual behavior:

```
ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" 
because pnpm-lock.yaml is not up to date with packages/renderer-vue/package.json
```

### Additional information:

 - `node -v` prints:
v18.12.1
 - Windows, macOS, or Linux?:
macOS
