### ISSUE TITLE
The effect of the registry path in the pnpm-lock.yaml

### ISSUE THREAD

**Issue by JackClown** [pnpm/pnpm#5769]
### Discussed in https://github.com/pnpm/pnpm/discussions/5753

<div type='discussions-op-text'>

<sup>Originally posted by **JackClown** December  5, 2022</sup>
I find that dependencies are prefixed with registry path like blew:
```yaml
    dependencies:
      '@babel/compat-data': registry.npmmirror.com/@babel/compat-data/7.19.4
      '@babel/core': registry.npmmirror.com/@babel/core/7.19.0
      '@babel/helper-validator-option': registry.npmmirror.com/@babel/helper-validator-option/7.18.6
      browserslist: registry.npmmirror.com/browserslist/4.21.3
      semver: registry.npmmirror.com/semver/6.3.0
```
does it means that the project will install packages with the registry?

but i find there is no registry path in another project's lock file

```yaml
    dependencies:
      call-bind: 1.0.2
      has-bigints: 1.0.2
      has-symbols: 1.0.3
      which-boxed-primitive: 1.0.2
```

how did that come about? 
please help 🙏
</div>

**Comment by zkochan** [comment]
what registry do you have configured in your `.npmrc`?

if you have `registry=https://registry.npmmirror.com`, then you'll get a lockfile like this:

```
    dependencies:
      call-bind: 1.0.2
      has-bigints: 1.0.2
      has-symbols: 1.0.3
      which-boxed-primitive: 1.0.2
```
