### ISSUE TITLE
Incorrect spec in shrinkwrap.yaml

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#587]
### Code to reproduce the issue:

```
pnpm i -S is-negative
```

### Expected behavior:

`shrinkwrap.yaml` contains the resolution for dependency as specified in `package.json`

```yaml
is-negative@^2.1.0:
  id: registry.npmjs.org/is-negative/2.1.0
  shasum: f0d86377aa15a64c34961f38ac2a9be2b40a1187
  tarball: 'https://registry.npmjs.org/is-negative/-/is-negative-2.1.0.tgz'
```

### Actual behavior:

```yaml
is-negative:
  id: registry.npmjs.org/is-negative/2.1.0
  shasum: f0d86377aa15a64c34961f38ac2a9be2b40a1187
  tarball: 'https://registry.npmjs.org/is-negative/-/is-negative-2.1.0.tgz'
```

**Comment by andreypopp** [comment]
That case is interesting — installing the package without version range:
```
% pnpm install package
```

There are two cases.

#### 1. Shrinkwrap has no info on that package

Basically in that case we need to generate the version range automatically for saving in `package.json` and `shrinkwrap.yaml`: for a resolution to some version `x.y.z` we should generate `^x.y.z` automatically — that's what I believe `npm` and `yarn` do.

#### 2. Shrinkwrap has some info on that package but from a resolution saved not from the root current package

In that case it makes sense either

- **A.** to always resolve the package. But that means we can accidentally update another shrinkwrap record — not sure if it's good or bad.
- **B.** Try to reuse a shrinkwrapped resolution by picking the one with the "latest" version.

**Comment by zkochan** [comment]
maybe the current shrinkwrap format has to be reviewed. Maybe it should reflect the dependency tree and resolve for each package separately

**Comment by zkochan** [comment]
I think we'll have to make the shinkwrap format more like what the npm-shrinkwrap looks like, where the same spec can be resolved to different versions

```yaml
version: 1
resolutions:
  registry.npmjs.org/@types/chalk/0.4.31:
    shasum: a31d74241a6b1edbb973cf36d97a2896834a51f9
    tarball: 'https://registry.npmjs.org/@types/chalk/-/chalk-0.4.31.tgz'
dependencies:
  '@types/chalk':
    resolved: registry.npmjs.org/@types/chalk/0.4.31
    dependencies:
      '@types/node':
        resolved: registry.npmjs.org/@types/chalk/0.4.31
```
