### ISSUE TITLE
pnpm config set command fails to configure in github actions

### ISSUE THREAD

**Issue by T3NED** [pnpm/pnpm#5889]
### What?
GitHub actions is failing to install a private package. I configure pnpm using the `pnpm config set` command to set the registry and auth token for the private package. Installation was working on version `7.19.0` up until the runner was using version `7.20.0`.  `7.20.0` implemented changes to the `pnpm config` command - I've tested all versions after `7.19.0`, and the job fails up to the latest version.

Checking the action logs, neither the registry or auth token are set when `pnpm install` is run.

### pnpm version:
v7.20.0+

### Code to reproduce the issue:
```yml
jobs:
    install-dependencies:
        name: Install dependencies
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Setup PNPM
              uses: pnpm/action-setup@v2
              with:
                  version: 7
                  run_install: false

            - name: Configure PNPM
              run: |
                  pnpm config set @MYORG:registry=https://npm.pkg.github.com
                  pnpm config set -- "//npm.pkg.github.com/:_authToken" "${{ secrets.PACKAGE_AUTH_TOKEN }}"

            - name: Resolve PNPM store path
              id: pnpm-store-path
              run: |
                  echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - name: Setup PNPM cache
              uses: actions/cache@v3
              with:
                  path: ${{ steps.pnpm-store-path.outputs.PNPM_STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install --frozen-lockfile
```

### Expected behavior:
The `pnpm config set` commands are run to set the registry and auth token, and the private package is installed.

### Actual behavior:
Neither the registry or auth token are set, therefore installation fails.

### Additional information:
- The commands that are run, and context of the commands are given in the code provided above
- I suspect it's something to do with where the `.npmrc` file is created in the GitHub runner
