### ISSUE TITLE
Fetching packages with docker inline cache mounted doesn't get cached - WARN  EXDEV: cross-device link not permitted 

### ISSUE THREAD

**Issue by JunlinPan-Crypto** [pnpm/pnpm#6064]
### pnpm version:
v7.27.0 
### Code to reproduce the issue:
Run docker buildx in Github Actions hosted runners (Ubuntu).

```yaml
- name: Build docker image
  uses: docker/build-push-action@v3
  with:
    context: .
    load: true
    tags: ${{ env.image }}
    build-args: |
      ...
    ssh: default
    cache-from: type=gha
    cache-to: type=gha,mode=max
```

Dockerfile:
```Dockerfile
COPY pnpm-lock.yaml ./

# Fetch all node modules purely based on the pnpm lock file and cache
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store pnpm fetch

COPY . .

RUN pnpm i --offline --frozen-lockfile
```

### Expected behavior:
Reuse packages stored in docker inline cache, not download every time.

### Actual behavior:
- Warn: WARN  EXDEV: cross-device link not permitted.
- Falling back to copying packages from store.
- Reused 0 packages.

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/90383710/217787957-1a5f0aca-4115-4900-8f6d-7979a2a28d62.png">

```
#19 31.94 Progress: resolved 1636, reused 0, downloaded 1610, added 1636, done
```
### Relavant issues
https://github.com/pnpm/pnpm/issues/3439
https://github.com/pnpm/pnpm/issues/3114#issuecomment-1237499901
https://github.com/pnpm/pnpm/discussions/3651

**Comment by thynson** [comment]
That's expected behavior. Due to using of hard link, pnpm store and project must be on same storage devices, while `--mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store` make `/root/.local/share/pnpm/store` on a different storage device.

**Comment by JunlinPan-Crypto** [comment]
@thynson  Then you mean it's not possible to cache pnpm store during docker build in Github Actions? Or any other cache approaches?

**Comment by thynson** [comment]
You may try `--package-import-method auto` or `--package-import-method copy` to let pnpm not to create hard link to see if it works for your situation.

**Comment by JunlinPan-Crypto** [comment]
> You may try `--package-import-method auto` or `--package-import-method copy` to let pnpm not to create hard link to see if it works for your situation.

It didn't work - `pnpm fetch --package-import-method copy(auto)`

The expected result is reusing all packages stored in Docker cache, rather than `Progress: resolved 1636, reused 0, downloaded 1610, added 1636, done`

**Comment by pamann** [comment]
Any workarounds/updates on this? Running into the same issue.

**Comment by Silbad** [comment]
Same issue for me when I put my .pnpm-store in my "users" folder (win11)

**Comment by thynson** [comment]
I recently update the CI pipeline and corresponding Dockerfile of my project, taking the advantage of the `--mount=type=cache` and it seems works well for a while. You can check the [Dockerfile](https://github.com/sensejs/sensejs/blob/main/Dockerfile) and the [Action file](https://github.com/sensejs/sensejs/blob/main/.github/workflows/main.yaml). 
As far as I can see, the difference with the one of @JunlinPan-Crypto is that the I'm using `docker/build-push-action@v4`

**Comment by michael-land** [comment]
@thynson 

I checked your workflow history and noticed that in your example repository, pnpm still downloads all the packages.


<img width="821" alt="CleanShot 2023-08-22 at 23 06 49@2x" src="https://github.com/pnpm/pnpm/assets/33362998/38e1674c-b1b1-4fb2-a252-9ff6df417f1e">

**Comment by thynson** [comment]
> I checked your workflow history and noticed that in your example repository, pnpm still downloads all the packages.

You're right. I think I misread some log, and it should be the case that `pnpm fetch --cache-from...` cached by docker, not the case that contents in `/root/.local/share/pnpm/store` were reused across build.

**Comment by maschwenk** [comment]
I think the downloads are still cached but instead of hard-linking it's just copying the files. This is a performance penalty but probably smaller perf penalty than having to fetch all the images from scratch?

**Comment by JunlinPan-Crypto** [comment]
It seems to able to cache after I specified the `platforms: linux/arm64` argument in `docker/build-push-action@v5` action.

pnpm version: 8.15.5 (latest)

Store cache:
<img width="1135" alt="image" src="https://github.com/pnpm/pnpm/assets/90383710/43b5288d-1744-47ee-a089-91b8833be9ac">

Cached:
<img width="1140" alt="image" src="https://github.com/pnpm/pnpm/assets/90383710/8604e3b4-41da-41bd-a230-70ea737ca946">

Workflow:

```yaml
     - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.image }}
          build-args: |
            APP_ENV=${{ inputs.environment }}
            GITHUB_REF_NAME=${{ github.ref_name }}
          secrets: |
            "token=${{ secrets.GITHUB_TOKEN }}"

         # Not sure if the platforms at play
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
```
