### ISSUE TITLE
compare lockfile changes

### ISSUE THREAD

**Issue by bvanjoi** [pnpm/pnpm#6113]
**Describe the user story**

A single pnpm-lockfile stores all the dependent versions of that repository, but in large projects, version changes often lead to git conflicts that are difficult to resolve. In order to make code review easier, we tried to find a way to help users quickly understand how versions of certain projects are changing.

**Describe the solution you'd like**

We know that although the version information is stored in a graph structure in pnpm-lockfile, the dependency versions of the project are actually in a tree structure, e.g.

```yaml
# lockfile
importers:
    packages/a:
         depdencies:
            lodash: 1.0.0
    packages/b:
         depdencies:
            lodash: 1.0.0

packages:
   /lodash/1.0.0
```

can be split into two lockfiles:

```yaml
# packages/a/lockfile
depdencies:
     lodash: 1.0.0

packages: 
    /lodash/1.0.0
```

```yaml
# packages/b/lockfile
dependencies:
    lodash: 1.0.0

packages: 
    /lodash/1.0.0
```

With this feature, for example, when a version change occurs on branch A, such as changing the lodash version to 1.0.1, then at some point, e.g. on ci, a warning can be given about the version of `packages/b/lodash` is different from the version in the lockfile of the master branch, thus preventing unintended changes.

--

I can implement this feature, but in the meantime I'm looking for more suggestions.

- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Comment by zkochan** [comment]
I can suggest two setting change to reduce conflicts:

```
use-lockfile-v6=true
resolution-mode=time-based
```

The new lockfile format should have less conflicts.

And with time-based resolution mode versions are upgraded less frequently, so conflicts should occur less frequently.

**Comment by bvanjoi** [comment]
> I can suggest two settings to reduce conflicts:
> 
> ```
> use-lockfile-v6=true
> resolution-mode=time-based
> ```
> 
> The new lockfile format should have less conflicts.
> 
> And with time-based resolution mode versions are upgraded less frequently, so conflicts should occur less frequently.

Very good idea, but we have a lot of old projects in our company and they don't have the means to accept the risk of version changes caused by configuration item changes, so I'm looking for ways to not change the lockfile.

**Comment by zkochan** [comment]
> We tried to find a way to help users quickly understand how versions of certain projects are changing.

What does this mean? Like a better diff for lockfiles?

**Comment by bvanjoi** [comment]
Yes, perhaps we could provide a way to `pnpm lock-compare lock1 lock2` that would call the `compare` function and show the exact difference.

For example.

```yaml
# lock1
importers:
    packages/a:
         depdencies:
            lodash: 1.0.0
    packages/b:
         depdencies:
            lodash: 1.0.0

packages:
   /lodash/1.0.0
```

```yaml
# lock2
importers:
    packages/a:
         depdencies:
            lodash: 1.0.0
    packages/b:
         depdencies:
            lodash: 1.0.1

packages:
   /lodash/1.0.0:
   /lodash/1.0.1:
```

Then executing `compare(lock1, lock2)` will return.

```js
{
  b: {
     // of course, it should not be just a simple string array, 
     // but an object containing a complete reference link.
    adding: ['lodash/1.0.1'], 
    eliminate: ['lodash/1.0.0']
  }
}
```

Executing `compare(lock2, lock1)` will return.

```js
{
  b: {
    add: ['lodash/1.0.0'],
    eliminate: ['lodash/1.0.1']
  }
}
```
