### ISSUE TITLE
EEXIST: file already exists, mkdir

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#617]
If `node_modules` is already symlinked then it fails with this error.

```
  1903 error pnpm:
    message:
      errno: -17
      code: "EEXIST"
      syscall: "mkdir"
      path: "/var/www/zzz/releases/20170209225127/node_modules"
    err:
      name: "Error"
      message: "EEXIST: file already exists, mkdir '/var/www/zzz/releases/20170209225127/node_modules'"
      code: "EEXIST"
      stack: "Error: EEXIST: file already exists, mkdir '/var/www/zzz/releases/20170209225127/node_modules'\n    at Error (native)\n"
```

The cause of it was using a capistrano-like deploy and sharing the `node_modules` dir between releases. This was to cache the node_modules between builds. Probably not neccessary anymore since there is a global store.

But there should be some kind of check and a better error message if `node_modules` already exists as a link.

### Code to reproduce the issue:

```
cd /dev/app
mkdir ../node_modules
npm init -s
/dev/app/node_modules -> /dev/node_modules
/dev/node_modules
pnpm i
```

### Expected behavior:

No error.

### Actual behavior:

```
EEXIST: file already exists, mkdir '/dev/app/node_modules'
```

### Additional information:

 - `node -v` prints: 6.5.0
 - Windows, OS X, or Linux?: macOS
