### ISSUE TITLE
Auth tokens configured by `pnpm config set` are not found by npm

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#6181]
The version `7.28.0` doesn't work, but the `7.27.1` works. Here's the relevant part of the config to make it work:

```yaml
publish:
  stage: publish
  before_script:
    - corepack enable
    - corepack prepare pnpm@7.27.1 --activate
    - pnpm config set "//${GITLAB_REGISTRY}:_authToken=${CI_JOB_TOKEN}"
```

_Originally posted by @navaru in https://github.com/pnpm/pnpm/issues/4937#issuecomment-1455139283_

This happens because `pnpm config set` writes to its own rc file at `~/.config/pnpm/rc`, which is not read by npm CLI (and pnpm publish run `npm publish` under the hood).

I think the solution should be to make pnpm run `npm config set` when auth tokens are configured.

**Comment by semiautomatix** [comment]
gitlab-ci.yml

```yaml
image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - npm config set "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}"
  script:
    - pnpm install --frozen-lockfile --strict-peer-dependencies
    - pnpm publish --publish-branch main --no-git-checks
```

I thought I'd double-check this doesn't work. No luck, I'm afraid.

```bash
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://gitlab.com/api/v4/projects/43729055/packages/npm/
npm ERR! need auth You need to authorize this machine using `npm adduser`
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-08T00_50_37_922Z-debug-0.log
```
