### ISSUE TITLE
Error setting up pnpm cache in github actions

### ISSUE THREAD

**Issue by brendaHuang** [pnpm/pnpm#6234]
Seeing the following error when following [this page](https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time) to set up pnpm cache.

```
Run PNPM_STORE=$(pnpm store path)
  PNPM_STORE=$(pnpm store path)
  echo "PNPM_STORE_ENV_VAR=$PNPM_STORE" >> $GITHUB_OUTPUT
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
Error: Unable to process file command 'output' successfully.
Error: Invalid format '/home/runner/setup-pnpm/node_modules/.bin/store/v[3]'
```

### pnpm version:
7
### Code to reproduce the issue:
yml file: 

```
name: Test Suite

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-and-lint:
    name: Runs Tests with Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
```
.npmrc
`use-node-version=16.19.0`

### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:
