### ISSUE TITLE
Not working with GitLab CI

### ISSUE THREAD

**Issue by ivanafanasyeu** [pnpm/pnpm#6539]
### pnpm version:
8+

### Code to reproduce the issue:
```yml
default:
  image: node:18.16.0
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store

deploy_preview:
  stage: deploy
  only:
    - master
  script:
    - pnpm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN
```

### Expected behavior:
working CI

### Actual behavior:
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.

### Additional information:
GitLab CI

**Comment by zkochan** [comment]
Try this:

```
  script:
    - pnpm setup
    - source ~/.bashrc
    - pnpm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN
```

**Comment by ivanafanasyeu** [comment]
```
default:
  image: node:18.16.0
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store

deploy_preview:
  stage: deploy
  only:
    - master
  script:
    - pnpm setup
    - source ~/.bashrc
    - pnpm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
    - release


  script:
    - pnpm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
```
![Screenshot 2023-05-19 at 21 49 20](https://github.com/pnpm/pnpm/assets/25664253/896ddb1d-b512-410c-a021-5ea32619d149)
