### ISSUE TITLE
Can not cache dependencies in Azure Pipelines

### ISSUE THREAD

**Issue by vixero-dev** [pnpm/pnpm#6554]
### pnpm version: 

8.5.1

### Code to reproduce the issue: 

The code mentioned in the [docs](https://pnpm.io/continuous-integration#azure-pipelines):

```yaml
variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store

steps:
  - task: Cache@2
    inputs:
      key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
      path: $(pnpm_config_cache)
    displayName: Cache pnpm

  - script: |
      corepack enable
      corepack prepare pnpm@latest-8 --activate
      pnpm config set store-dir $(pnpm_config_cache)
    displayName: "Setup pnpm"

  - script: |
      pnpm install
      pnpm run build
    displayName: "pnpm install and build"
```

### Expected behavior: 

The node_modules are cached.

### Actual behavior:

Task -> Post-job: Cache pnpm
```
There is a cache miss.
tar: could not chdir to 'D:\a\1\.pnpm-store'
```

### Additional information:

 - `node -v` prints: node 18.16.0
 - Windows, macOS, or Linux?: Windows
 - vmImage: windows-2022, Version: 20230508.3

**Comment by vixero-dev** [comment]
Looks like the `store-dir` variable is not being set.

After changing this part:

```yaml
  - script: |
      corepack enable
      corepack prepare pnpm@latest-8 --activate
      pnpm config set store-dir $(pnpm_config_cache)
    displayName: "Setup pnpm"
```

to this:

```yaml
  - script: |
      corepack enable
      corepack prepare pnpm@latest-8 --activate
    displayName: "setup pnpm"

  - script: pnpm config set store-dir $(pnpm_config_cache)
    displayName: "setup pnpm config"
```

I stopped experiencing this issue.
