### ISSUE TITLE
If install an already installed package with tgz, only specificers are changed

### ISSUE THREAD

**Issue by WhiteKiwi** [pnpm/pnpm#6612]
### pnpm version:
7.32.4
8.6.0

### Code to reproduce the issue:
e.g. under the following circumstances, Running `pnpm add https://example.com/foo.tgz` will change only the specificers.
When installed for the first time, such as `pnpm add https://example.com/bar.tgz`, it works normally.
```json
{
  "name": "service",
  "dependencies": {
    "foo": "^1.0.0"
  }
}
```

### Expected behavior:
pnpm 7 lockfile
```
services/service:
    specifiers:
      'foo': https:/example.com/foo.tgz
    dependencies:
      'foo': '@https+/example.com/foo.tgz'
```

### Actual behavior:
pnpm 7 lockfile
```
services/service:
    specifiers:
      'foo': https:/example.com/foo.tgz
    dependencies:
      'foo': 1.0.0
```

### Additional information:
If you run `pnpm add foo.tgz` one more time in the following state, it becomes expected.
```
services/service:
    specifiers:
      'foo': https:/example.com/foo.tgz
    dependencies:
      'foo': 1.0.0
```
As a result, if you attempt to install an already installed package as tgz, it appears that you need to run the pnpm add command twice.

Thanks 🙇 

 - `node -v` prints: v18.16.0
 - Windows, macOS, or Linux?: macOS
