### ISSUE TITLE
Making the shrinkwrap files smaller

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#664]
The shrinkwrap files contain too much redundant information.

Here's a resolution example:

```yaml
  registry.npmjs.org/yargs/6.6.0:
    dependencies:
      camelcase: registry.npmjs.org/camelcase/3.0.0
      cliui: registry.npmjs.org/cliui/3.2.0
      decamelize: registry.npmjs.org/decamelize/1.2.0
      get-caller-file: registry.npmjs.org/get-caller-file/1.0.2
      os-locale: registry.npmjs.org/os-locale/1.4.0
      read-pkg-up: registry.npmjs.org/read-pkg-up/1.0.1
      require-directory: registry.npmjs.org/require-directory/2.1.1
      require-main-filename: registry.npmjs.org/require-main-filename/1.0.1
      set-blocking: registry.npmjs.org/set-blocking/2.0.0
      string-width: registry.npmjs.org/string-width/1.0.2
      which-module: registry.npmjs.org/which-module/1.0.0
      y18n: registry.npmjs.org/y18n/3.2.1
      yargs-parser: registry.npmjs.org/yargs-parser/4.2.1
    resolution:
      shasum: 782ec21ef403345f830a808ca3d513af56065208
      tarball: 'https://registry.npmjs.org/yargs/-/yargs-6.6.0.tgz'
```

Almost all deps are resolved from npmjs.org, as a consequence, only the versions can be used to resolve npm dependencies

```yaml
  registry.npmjs.org/yargs/6.6.0:
    dependencies:
      camelcase: 3.0.0
      cliui: 3.2.0
      decamelize: 1.2.0
      get-caller-file: 1.0.2
      os-locale: 1.4.0
      read-pkg-up: 1.0.1
      require-directory: 2.1.1
      require-main-filename: 1.0.1
      set-blocking: 2.0.0
      string-width: 1.0.2
      which-module: 1.0.0
      y18n: 3.2.1
      yargs-parser: 4.2.1
    resolution:
      shasum: 782ec21ef403345f830a808ca3d513af56065208
      tarball: 'https://registry.npmjs.org/yargs/-/yargs-6.6.0.tgz'
```

When the tarball resolution has a standard format, it can be skipped as well, so the resolution can be just the shasum:

```yaml
  registry.npmjs.org/yargs/6.6.0:
    dependencies:
      camelcase: 3.0.0
      cliui: 3.2.0
      decamelize: 1.2.0
      get-caller-file: 1.0.2
      os-locale: 1.4.0
      read-pkg-up: 1.0.1
      require-directory: 2.1.1
      require-main-filename: 1.0.1
      set-blocking: 2.0.0
      string-width: 1.0.2
      which-module: 1.0.0
      y18n: 3.2.1
      yargs-parser: 4.2.1
    resolution: 782ec21ef403345f830a808ca3d513af56065208
```

A new property called `registry` should be added to save the default registry origin. If a scoped dep has a different registry, the whole id should be used

```yaml
dependencies:
  yargs@^6.0.0: 6.0.0
registry: http://registry.npmjs.org
packages:
  registry.npmjs.org/yargs/6.6.0:
    dependencies:
      yargs-parser: 4.2.1
      @foo/bar: sinopia/@foo/bar/1.0.0
    resolution: 782ec21ef403345f830a808ca3d513af56065208
  sinopia/@foo/bar/1.0.0:
    resolution:
      shasum: 782ec21ef403345f830a808ca3d513af56065208
      tarball: http://sinopia/-/....
version: 2
```
