### ISSUE TITLE
pnpm doesn't recognise cached/installed version of node and keeps downloading it

### ISSUE THREAD

**Issue by antony** [pnpm/pnpm#6926]
This is costing us hours of wasted time per week, so I'm raising it in the company discussion thread too.

### pnpm version:

8.6.2

### Code to reproduce the issue:

seems to happen on github actions exclusively. simply running:

```
pnpm i
```

We cache the node version downloaded by running the following:

```
      - uses: actions/cache@v3
        name: cache node
        with:
          path: /home/runner/.local/share/pnpm
          key: ${{ runner.os }}-pnpm-node-cache
          restore-keys: |
            ${{ runner.os }}-pnpm-node-cache-
```

We used to use a pnpm command (I forget which) to determine the cache dir name, but this in itself caused pnpm to download node (!!!) and thus it would stick even before the caching happened. So now we hardcode it, based on looking at where pnpm installs node to.

### Expected behavior:

PNPM sees that node is installed on the machine, and doesn't re-download it.

### Actual behavior:

PNPM insists on downloading node from nodejs.org which frequently returns gateway errors or times out

![Screenshot from 2023-08-09 12-20-36](https://github.com/pnpm/pnpm/assets/218949/3182d853-9a31-44d0-90c2-584b1b29cd5a)

### Additional information:

 - `node -v` prints:
v19.9.0
 - Windows, macOS, or Linux?:
 - Ubuntu Linux
