### ISSUE TITLE
After migrating from v7 to v8 resolve-peers-from-workspace-root does not work as expected

### ISSUE THREAD

**Issue by savolkov** [pnpm/pnpm#6944]
Hey.

After migrating from v7.30.0 to v8.6.11 it seems that `resolve-peers-from-workspace-root` set to `true` does not work properly (or most likely I'm missing something).

#### .npmrc:
```
auto-install-peers = true
link-workspace-packages = false
resolve-peers-from-workspace-root=true
save-prefix = ""
save-workspace-protocol = rolling
strict-peer-dependencies = false
```

#### Monorepo configuration
We use multipackage monorepo with the following structure:
1. **Root** `package.json` with all dependencies installed and versions specified.
```json
...
"dependencies": {
    "slate": "0.94.1",
    ...
}
...
```
2. In **packages** we have own files `packages/packageName/package.json` with all the deps described as peerDependencies:
```json
...
"peerDependencies": {
    "slate": "*",
    ...
}
....
```

### Steps to reproduce
1. Bump `slate` version in root
2. Run `pnpm i`
### Expected behavior (as it was on v7):
In `pnpm-lock.yaml` there is only the latest version. In package's dependencies `'*'` specifier resolves to the one specified in root `package.json`.
### Actual behavior:
In `pnpm-lock.yaml` there are an old version and a new one. In package's dependencies `'*'` is still resolved to an older version.
```yaml
  .:
    dependencies:
      slate:
        specifier: 0.94.1
        version: 0.94.1
  packages/packageName:
    dependencies:
      slate:
        specifier: '*'
        version: 0.84.0
```
### Additional information:
- `node -v` prints
```
> node -v
v16.15.1
```
- OS
Reproduced both on Windows and Mac
