### ISSUE TITLE
Cannot resolve external git packages

### ISSUE THREAD

**Issue by wintercounter** [pnpm/pnpm#707]
### Code to reproduce the issue:
Add a custom git url as package.
```
"my-custom-package": "git+ssh://git@mygit.site/package.git#v0.1.7",
```
### Expected behavior:
Resolves package
### Actual behavior:
Does not resolve package.

**Comment by zkochan** [comment]
@wintercounter could you please recheck with latest pnpm. This might have been fixed by #717. If not, add the error stack trace that will be at the end of the `pnpm-debug.log` file

**Comment by FalloutPL** [comment]
$ pnpm -v
0.65.4

Not fixed:

URL from our gitlab: ```git@site:project/repo.git```
package: ```"git+ssh://git@site:project/repo.git#master"```
```
   err: 
      name: "Error"
      message: "Command failed: git ls-remote --refs ssh://git@git.pf.com.pl/:eniro-crm/ecrm-fakerjs.git master\nGitLab: The project you were looking for could not be found.\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
      code: 128
   ```

it changes url to:

```ssh://git@site/:project/repo.git```

than 

```ssh://git@site/project/repo.git```

so

there is unwanted ```:``` in parsed url
