### ISSUE TITLE
Issue with switching to pnpm in existing project - invalid argument for autoprefixer

### ISSUE THREAD

**Issue by tiriana** [pnpm/pnpm#710]
### Code to reproduce the issue:

I simple installed pnpm globally (```npm install -g pnpm```) and ran ```pnpm i``` in existing project. I got this error:

ERROR EINVAL: invalid argument, readlink '/path/to/the/project/node_modules/autoprefixer'

### Expected behavior:

installation works 

### Actual behavior:

installation doesn't work

### Additional information:

 - `node -v` prints: v6.9.4
 - Windows, OS X, or Linux?: Ubuntu 16.04

### pnpm-debug:

```
---
  0 error pnpm: 
    message: 
      errno: -22
      code: "EINVAL"
      syscall: "readlink"
      path: "/path/to/the/project/node_modules/autoprefixer"
    err: 
      name: "Error"
      message: "EINVAL: invalid argument, readlink '/path/to/the/project/node_modules/autoprefixer'"
      code: "EINVAL"
      stack: "Error: EINVAL: invalid argument, readlink '/path/to/the/project/node_modules/autoprefixer'\n    at Error (native)"
```
