### ISSUE TITLE
`pnpm dlx` looks for patches in a wrong location

### ISSUE THREAD

**Issue by moltar** [pnpm/pnpm#7183]
### Last pnpm version that worked

8.8.0

### pnpm version

8.9.0

### Code to reproduce the issue

N/A

### Expected behavior

`pnpm dlx` should not try to install patches

### Actual behavior

In GitHub Actions, pnpm tries to look for patches, but in an odd location.

```
 ENOENT  ENOENT: no such file or directory, open '/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/dlx-1527/patches/rollup@3.28.1.patch'
```

### Additional information

This started happening for us as the pnpm `8.9.0` got released, as our version was pinned at `8` (major) and literally the same hour PRs started to fail with the error above. So I think it was something in that major release.

Action was setup this way:

```yaml
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
```

### Node.js version

18.12.1

### Operating System

Linux
