### ISSUE TITLE
Installing private node package from Bitbucket changing its codeline in package.json

### ISSUE THREAD

**Issue by w3fo** [pnpm/pnpm#7342]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.10.5

### Which area(s) of pnpm are affected? (leave empty if unsure)

Lockfile

### Reproduction steps

I have a private node package on bitbucket which is loading with an app-password in package.json, so it will also work with deployment pipelines:

```
{
  "dependencies": {
    "my-package": "git+https://<bitbucket-user>:<bitbucket-app-password>@bitbucket.org/my-workspace/my-package.git"
  }
}
```

### Describe the Bug

It runs as expected and loads the package but everytime I run an update/install locally it changes the line into

```
{
  "dependencies": {
    "my-package": "bitbucket:my-workspace/my-package",
  }
}
```

I assume this happens because of me having a git ssh connection to bitbucket. The second one still works locally but breaks when I am deploying. Now everytime I want to deploy I have to change the codeline back by hand and delete the pnpm-lock.yaml file.

### Expected Behavior

Leaving the codeline as it is.

### Which Node.js version are you using?

18.17.1

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by JonathanIcon** [comment]
I am experiencing the same issue

**Comment by sate99** [comment]
I am experiencing the same issue using the latest version of pnpm (8 and 9).

**Comment by AndreMaz** [comment]
Hey @zkochan I'm facing the same issue.
When I execute

```bash
pnpm add git+https://x-token-auth:<BITBUCKER_ACCESS_TOKEN>@bitbucket.org/my-org/my-repo.git
```
> Link to bitbucket's docs about access token: https://support.atlassian.com/bitbucket-cloud/docs/access-tokens/

I end up with the following entry in my `package.json`
```bash
"my-repo": "bitbucket:my-org/my-repo",
```
and the following entry `pnpm-lock.yaml`
```yaml
my-repo@git+https://git@bitbucket.org:my-org/my-repo.git#1e37d6cc8bb4a22a897b01774e6ffd04a8a2617b:
  resolution: {commit: 1e37d6cc8bb4a22a897b01774e6ffd04a8a2617b, repo: git@bitbucket.org:my-org/my-repo.git, type: git}
  version: 0.1.0
  engines: {node: '>= 20.x.x'}

my-repo@git+https://git@bitbucket.org:my-org/my-repo.git#1e37d6cc8bb4a22a897b01774e6ffd04a8a2617b:
  dependencies:
    date-fns: 4.1.0
    date-fns-tz: 3.2.0(date-fns@4.1.0)
    lodash: 4.17.21  
```

While this works locally (because I have ssh git configured) it fails on my CI/CD pipelines.

Is there a way of disabling this behavior? 

With npm and yarn things seem to be working. I mean, here' the yarn.lock entry
```yaml
"my-repo@git+https://x-token-auth:<BITBUCKER_ACCESS_TOKEN>@bitbucket.org/my-org/my-repo.git":
  version "0.1.0"
  resolved "git+https://x-token-auth:<BITBUCKER_ACCESS_TOKEN>@bitbucket.org/my-org/my-repo.git#1e37d6cc8bb4a22a897b01774e6ffd04a8a2617b"
  dependencies:
    date-fns "^4.1.0"
    date-fns-tz "^3.2.0"
    lodash "^4.17.21"
```
and here's package-lock.json
```json
"node_modules/my-repo": {
  "version": "0.1.0",
  "resolved": "git+https://x-token-auth:<BITBUCKER_ACCESS_TOKEN>@bitbucket.org/my-org/my-repo.git#1e37d6cc8bb4a22a897b01774e6ffd04a8a2617b",
  "dependencies": {
    "date-fns": "^4.1.0",
    "date-fns-tz": "^3.2.0",
    "lodash": "^4.17.21"
  },
  "engines": {
    "node": ">= 20.x.x"
  }
},
```
