### ISSUE TITLE
Should a relative path file package cause an absolute path in shrinkwrap.yaml?

### ISSUE THREAD

**Issue by staltz** [pnpm/pnpm#744]
### Code to reproduce the issue:

In package.json for the project I'm authoring:

```json
...
  "devDependencies": {
    "react-native": "file:./mock-react-native"
  },
...
```

### Expected behavior:

shrinkwrap.yaml to show something like

```
local .%2Fmock-react-native:
    resolution:
      root: ./mock-react-native
      type: directory
```

### Actual behavior:

shrinkwrap.yaml shows

```
local/%2FUsers%2Fstaltz%2Fsecret%2Fpath%2Ftoproject%2Fmock-react-native:
    resolution:
      root: /Users/staltz/secret/path/toproject/mock-react-native
      type: directory
```

### Additional information:

This issue is related to https://github.com/pnpm/pnpm/issues/729 because this is only a problem if shrinkwrap.yaml is supposed to be committed in a VCS. Until then, I'm unwilling to put the absolute path in the shrinkwrap, and I suspect it wouldn't even work once other users pick it up from VCS.

PS: thanks for pnpm, I like it a lot.
