### ISSUE TITLE
Docker - `No package.json (or package.yaml, or package.json5) was found in `

### ISSUE THREAD

**Issue by DavDeDev** [pnpm/pnpm#7910]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

8.15.6

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/CC-Comp308001-Group04/pulsecare-web

### Reproduction steps

I am just building this dockerfile, which is extended from the sample provided by [pnpm](https://pnpm.io/docker#example-1-build-a-bundle-in-a-docker-container):
```dockerfile
FROM node:18-alpine as base
ENV NEXT_TELEMETRY_DISABLED 1
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV NEXT_TELEMETRY_DISABLED 1
# enbable corepack to use pnpm
RUN corepack enable
COPY . /pulsecare-webapp
WORKDIR /pulsecare-webapp
# Exposing port for when NOT running with docker-compose
EXPOSE 3000
# Args from .env file 
ARG DATABASE_URL
ARG AUTH_URL
ARG AUTH_SECRET
ARG AUTH_GOOGLE_ID
ARG AUTH_GOOGLE_SECRET

FROM base AS deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
# Trying to freshly install prisma client every time as suggested here: https://github.com/prisma/prisma/issues/7234#issuecomment-846606919
RUN pnpm dlx prisma generate --schema=prisma/schema.prisma


FROM deps as development
# RUN ls -la node_modules/.prisma/client
ENV PORT 3000
CMD ["pnpm", "dev"]


FROM deps as production-bundle
# set hostname to localhost
ENV HOSTNAME "0.0.0.0"
ENV DATABASE_URL=$DATABASE_URL  
ENV AUTH_URL=$AUTH_URL
ENV AUTH_SECRET=$AUTH_SECRET
ENV AUTH_GOOGLE_ID=$AUTH_GOOGLE_ID
ENV AUTH_GOOGLE_SECRET=$AUTH_GOOGLE_SECRET
RUN echo $DATABASE_URL
RUN echo $AUTH_URL
RUN echo $AUTH_SECRET
RUN pnpm build

FROM production-bundle as production
CMD ["pnpm", "start"]

```

and docker-compose:
```yaml
version: "3.1"
services:
  mongo6:
    profiles:
      - dev
    build:
      context: ./mongodb_rs
      args:
        MONGO_VERSION: 6
    environment:
      # https://github.com/prisma/prisma/issues/11925
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27018
      # Use "mongo" instead of "mongosh" before v5.0
      MONGO_COMMAND: "mongosh"
    ports:
      - "27018:27018"
    restart: always
    # networks:
    #   - pulsecare-net

  web_prod:
    profiles:
      - prod
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    ports:
      - "3000:3000"
  web_dev:
    profiles:
      - dev
    restart: always
    environment:
      # README: https://github.com/prisma/prisma/discussions/23790#discussioncomment-9060992
      - DATABASE_URL=mongodb://mongo6:27018/pulsecare-web?replicaSet=rs0&retryWrites=true&w=majority&directConnection=true
      # For WSL: https://www.reddit.com/r/nextjs/comments/1638ec6/comment/jy1h8ys/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
      - WATCHPACK_POLLING=true
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - mongo6
    links:
      - mongo6
    # networks:
    #   - pulsecare-net
    # This is only for hot reload in development
    volumes:
      - ../:/pulsecare-webapp
      - /pulsecare-webapp/node_modules
      - /pulsecare-webapp/.next
```

I am running ` docker compose -f .\docker\docker-compose.yaml --profile dev up --build  -V`

### Describe the Bug

This happened already in the past and I managed to fix it by running `npx pnpm install --global pnpm` on my machine (e.g., not included in Dockerfile) as recommended [here](https://github.com/pnpm/pnpm/issues/4645#issuecomment-1200301076) but after I cleaned Docker cache today this log doesn't go away anymore and the container won't start.
```sh
 `ERR_PNPM_NO_IMPORTER_MANIFEST_FOUND  No package.json (or package.yaml, or package.json5) was found in "/pulsecare-webapp".`

```

### Expected Behavior

The container should build normally and start the NextJs App on localhost:3000

### Which Node.js version are you using?

18-alpine

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

FROM node:18-alpine as base
I am running Docker in WSL (latest version) on Windows
