### ISSUE TITLE
ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY with relative local dependency (difference between windows and linux CI?)

### ISSUE THREAD

**Issue by Ryex** [pnpm/pnpm#7955]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

9.0.2

### Which area(s) of pnpm are affected? (leave empty if unsure)

Lockfile

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Ryex/ic10emu/actions/runs/8731724803/job/23957592473

### Reproduction steps

- add a dependency in the form of `"ic10emu_wasm": "file:../ic10emu_wasm/pkg",`
-  create lockfile using fresh install of 9.0.2 and empty `node_modules` with `pnpm install` under windows, no issues
- push to github
- use workflow to install latest pnpm, get `v9.0.2`
- trigger `pnpm install` in workflow
- get

```
Lockfile is up to date, resolution step is skipped
 ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for 'ic10emu_wasm@file:../ic10emu_wasm/pkg' in pnpm-lock.yaml
```

 - look at [lockfile](https://github.com/Ryex/ic10emu/blob/main/www/pnpm-lock.yaml) and see no issues

```yaml
 dependencies:
  // ...
  ic10emu_wasm:
    specifier: file:../ic10emu_wasm/pkg
    version: file:../ic10emu_wasm/pkg
  ic10lsp_wasm:
    specifier: file:../ic10lsp_wasm/pkg
    version: file:../ic10lsp_wasm/pkg
   // ...
   
packages:

   // ...

   file:../ic10emu_wasm/pkg:
    resolution: {directory: ../ic10emu_wasm/pkg, type: directory}
    name: ic10emu_wasm
    dev: false

  file:../ic10lsp_wasm/pkg:
    resolution: {directory: ../ic10lsp_wasm/pkg, type: directory}
    name: ic10lsp_wasm
    dev: false
    
```

### Describe the Bug

pnpm says lockfile missing a entry for a dependency specified as a relative directory
inspection of that lockfile reveals that the entry for the dependency is present

### Expected Behavior

`pnpm install` to work with no issues as it has previously

### Which Node.js version are you using?

windows:  v21.7.1  action runner: v18.20.2

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu   22.04.4   LTS (guthub action runner)
