### ISSUE TITLE
peerDependenciesMeta.optional ignored after new `pnpm install`

### ISSUE THREAD

**Issue by qraynaud** [pnpm/pnpm#8142]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.1.3

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver, Lockfile

### Reproduction steps

I have no exact reproduction step right now. I'm still trying to create a minimal reproduction sample. I'm posting this right now just in case you might have an idea already about why I'm getting this.

### Describe the Bug

We are trying to update from `pnpm@8` to `pnpm@9`. We are deleting the `pnpm-lock.yaml` and the resulting install works fine (after some tweaking). The issue is that once the `pnpm-lock` is generated, if we do another `pnpm install`, the lockfile changes and a lot of optional peer deps are installed even though no package in our install is referencing them.
2 examples of these are `react-native` that gets installed with the `@tanstack/react-query@4` package. Here are its related `package.json` entries:
```json
"peerDependencies": {
  "react": "^16.8.0 || ^17.0.0 || ^18.0.0",
  "react-dom": "^16.8.0 || ^17.0.0 || ^18.0.0",
  "react-native": "*"
},
"peerDependenciesMeta": {
  "react-dom": {
    "optional": true
  },
  "react-native": {
    "optional": true
  }
}
```
And the same thing happens with `node-fetch@2` that pulls `encoding` while we are not using it:
```yaml
"peerDependencies": { 
    "encoding": "^0.1.0"
},
"peerDependenciesMeta": {
    "encoding": {
        "optional": true
    }
},
```

It produces these kind of entries in the `pnpm-lock.yaml`:
```yaml
'@tanstack/react-query@4.36.1(react-dom@17.0.2(react@17.0.2))(react-native@0.74.1(@babel/core@7.4.3)(@babel/preset-env@7.20.2(@babel/core@7.21.0))(@types/react@17.0.2)(react@17.0.2))(react@17.0.2)':
  dependencies:
    '@tanstack/query-core': 4.36.1
    react: 17.0.2
    use-sync-external-store: 1.2.2(react@17.0.2)
  optionalDependencies:
    react-dom: 17.0.2(react@17.0.2)
    react-native: 0.74.1(@babel/core@7.4.3)(@babel/preset-env@7.20.2(@babel/core@7.21.0))(@types/react@17.0.2)(react@17.0.2)

'@tanstack/react-query@4.36.1(react-dom@17.0.2(react@17.0.2))(react-native@0.74.1(@babel/core@7.4.3)(@babel/preset-env@7.20.2(@babel/core@7.4.3))(@types/react@17.0.2)(encoding@0.1.13)(react@17.0.2))(react@17.0.2)':
  dependencies:
    '@tanstack/query-core': 4.36.1
    react: 17.0.2
    use-sync-external-store: 1.2.2(react@17.0.2)
  optionalDependencies:
    react-dom: 17.0.2(react@17.0.2)
    react-native: 0.74.1(@babel/core@7.4.3)(@babel/preset-env@7.20.2(@babel/core@7.4.3))(@types/react@17.0.2)(encoding@0.1.13)(react@17.0.2)

'@tanstack/react-query@4.36.1(react-dom@17.0.2(react@17.0.2))(react-native@0.74.1(@babel/core@7.4.3)(@babel/preset-env@7.20.2(@babel/core@7.4.3))(@types/react@17.0.2)(react@17.0.2))(react@17.0.2)':
  dependencies:
    '@tanstack/query-core': 4.36.1
    react: 17.0.2
    use-sync-external-store: 1.2.2(react@17.0.2)
  optionalDependencies:
    react-dom: 17.0.2(react@17.0.2)
    react-native: 0.74.1(@babel/core@7.4.3)(@babel/preset-env@7.20.2(@babel/core@7.4.3))(@types/react@17.0.2)(react@17.0.2)
```

This creates multiple versions of the lib that then makes everything fail because there should be only one in the build.

What I find odd is that in the generated `pnpm-lock` the optionalPeerDeps are denoted as optionalDeps. Maybe that’s what is ultimately causing the issue?

### Expected Behavior

The optional peer dependencies should not be installed and we should keep a single dep for the lib.

### Which Node.js version are you using?

20.11.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu@22.04.4
