### ISSUE TITLE
Can't use specifier for a snapshot dependency in the lock file

### ISSUE THREAD

**Issue by gabrielmfern** [pnpm/pnpm#8171]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.1.2

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver, Lockfile

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/gabrielmfern/pnpm-resolution-issue-repro

### Reproduction steps

1. Check that the resolution of `@types/react` for `types-react-dom` is an exact version not a specifier
2. Try adding a specifier into the snapshot for `types-react-dom` by changing it to:
```yaml
  types-react-dom@19.0.0-rc.0:
    dependencies:
      '@types/react': 
        specifier: npm:types-react@rc
        version: types-react@19.0.0-rc.0
```
3. Confirm that it errors when running `pnpm install`

### Describe the Bug

I was specifically trying to upgrade the React's types package to React 19 by changing the dependencies with something like:

```json
{
  "devDependencies": {
    "@types/react": "npm:types-react@rc",
    "@types/react-dom": "npm:types-react-dom@rc",
  }
}
```

But, since `types-react-dom` has `@types/react` as a dependency, I would expect pnpm to resolve into using `types-react` as `@types/react` instead of a published version of `@types/react`, but, it apparently resolves into using another resolved version of `@types/react` in my workspace.

After noticing this happening, I tried going through the lock file to see if I could manually solve the resolution of it, which was something like:

```yaml
importers:
  project:
    devDependencies:
      '@types/react':
        specifier: npm:types-react@rc
        version: types-react@19.0.0-rc.0
      '@types/react-dom':
        specifier: npm:types-react-dom@rc
        version: types-react-dom@19.0.0-rc.0
snapshots:
  types-react-dom@19.0.0-rc.0:
    dependencies:
      '@types/react': 18.2.47
```

And then I tried changing the snapshot to the following to fix the issue:

```diff
importers:
  project:
    devDependencies:
      '@types/react':
        specifier: npm:types-react@rc
        version: types-react@19.0.0-rc.0
      '@types/react-dom':
        specifier: npm:types-react-dom@rc
        version: types-react-dom@19.0.0-rc.0
snapshots:
  types-react-dom@19.0.0-rc.0:
    dependencies:
-      '@types/react': 18.2.47
+      '@types/react':
+        specifier: npm:types-react@rc
+        version: types-react@19.0.0-rc.0

```

And I was met with the following error:

```
 ERROR  ref.startsWith is not a function

pnpm: ref.startsWith is not a function
    at refsByPkgNames.reduce.depPaths (/corepack/pnpm/9.1.2/dist/pnpm.cjs:137562:17)
    at Array.reduce (<anonymous>)
    at parseDepRefs (/corepack/pnpm/9.1.2/dist/pnpm.cjs:137561:29)
    at pkgAllDeps (/corepack/pnpm/9.1.2/dist/pnpm.cjs:137530:83)
    at pickPkgsWithAllDeps (/corepack/pnpm/9.1.2/dist/pnpm.cjs:137485:7)
    at filterLockfileByImportersAndEngine (/corepack/pnpm/9.1.2/dist/pnpm.cjs:137453:52)
    at filterLockfileByEngine (/corepack/pnpm/9.1.2/dist/pnpm.cjs:137444:14)
    at headlessInstall (/corepack/pnpm/9.1.2/dist/pnpm.cjs:174676:74)
    at async _install (/corepack/pnpm/9.1.2/dist/pnpm.cjs:192101:33)
    at async mutateModules (/corepack/pnpm/9.1.2/dist/pnpm.cjs:191966:23)
```

### Expected Behavior

I would expect that it either would work after changing the lock file, or it would be resolving it properly based on the current package instead of the version in the workspace or the latest version.

### Which Node.js version are you using?

20.11.1

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Arch Linux

**Comment by KSXGitHub** [comment]
> Can't use specifier for a snapshot dependency in the lock file

This is not your real problem, your real problem is that you want to use `types-react` in place of `@types/react`, correct?

Is [overrides](https://pnpm.io/package_json#pnpmoverrides) sufficient?

```json
{
  "pnpm": {
    "overrides": {
      "@types/react": "types-react@rc"
    }
  }
}
```

**Comment by gabrielmfern** [comment]
@KSXGitHub I suppose, yeah. I have tried overrides, they are enabled on [the repro I made](https://github.com/gabrielmfern/pnpm-resolution-issue-repro) actually, but it doesn't make any difference. 

My thinking, coming from someone unfamiliar with pnpm internals, is that pnpm can't resolve it from the override precisely because it can't use specifiers on snapshot dependencies.

**Comment by KSXGitHub** [comment]
`overrides` should be at top-level `package.json`.

**Comment by gabrielmfern** [comment]
Oh, didn't know that. Thanks for the heads-up. Still, though, it resolves to a set version instead of the specifier:

```yaml
  types-react-dom@19.0.0-rc.0:
    dependencies:
      '@types/react': 18.3.3
```

**Comment by KSXGitHub** [comment]
> Still, though, it resolves to a set version instead of the specifier

I have cloned your repo and set `pnpm.overrides` then run `pnpm install`. This is the result:

![lockfile screenshot](https://github.com/pnpm/pnpm/assets/11488886/61f5d42c-7f30-4258-a98c-22a83024ef6a)

I suspect you set `overrides` instead of `pnpm.overrides`. You should double check. Is your `overrides` inside a `pnpm` object?

**Comment by gabrielmfern** [comment]
You are right, I misconfigured it again, sorry for not reading the docs thoroughly enough on this, but, the issue still seems to persist. 

Also, from the part of the lock file you shared, I still think I haven't got my issue across clearly enough though, so let me go through it again. `types-react-dom` has a dependency on `@types/react`, specifically it has `"@types/react": "*"`. The problem, then, is that the version that pnpm is resolving for this specific dependency (`18.3.3`) is not the same as the override (`npm:types-react@rc`).

My initial thinking was that pnpm should resolve it from my own specified version for `@types/react` (which is `npm:types-react@rc`), but I guess that is out of pnpm's scope. This not working with the override still seems to me like an issue, though, wonder what you think about this. Let me know if I'm being clear enough.

<details><summary>Small note on when the issue happens</summary>

  The issue doesn't actually seem to happen when you depend directly on `types-react-dom`.  The snapshots section I've been mentioned then looks like:
  
  ```yaml
    types-react-dom@19.0.0-rc.0:
      dependencies:
        '@types/react': types-react@19.0.0-rc.0
  ```

  Which I guess I can manually add in as a workaround. But this is what it should be like with the proper override.
</details>

**Comment by KSXGitHub** [comment]
@gabrielmfern I think I get what you mean: You are referring to the fact that even though `@types/react` has been overridden, `types-react-dom` still depends on `@types/react` instead of `types-react`. As seen in the snapshot section of the lockfile:

```yaml
snapshots:
  # ...

  types-react-dom@19.0.0-rc.0:
    dependencies:
      '@types/react': 18.3.3
```

I have inspect the problem and found that the problem is from `with-react-19/package.json`. You may change it to the following:

```json
{
  "name": "with-react-19",
  "devDependencies": {
    "@types/react": "18.3.3",
    "@types/react-dom": "18.3.0"
  }
}
```

The snapshots in the lockfile should now be as you desired:

```yaml

snapshots:

  csstype@3.1.3: {}

  types-react-dom@19.0.0-rc.0:
    dependencies:
      '@types/react': types-react@19.0.0-rc.0

  types-react@19.0.0-rc.0:
    dependencies:
      csstype: 3.1.3
```
