### ISSUE TITLE
Better support sets of dependencies that should be on the same version in pnpm catalogs

### ISSUE THREAD

**Issue by gluxon** [pnpm/pnpm#8245]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

The `catalog:` protocol allows developers to deduplicate dependency specifiers across different `package.json` files in a repo.

There are some sets of dependencies (typically ones published from a monorepo) that follow similar version schemes and ideally upgrade "_together_". For example, you generally want to keep `react`, `react-dom`, and `react-is` on the same version.

```yaml
# pnpm-workspace.yaml

catalog:
  react: ^18.3.1
  react-dom: ^18.3.1
  react-is: ^18.3.1
```

### Describe the solution you'd like

It would be convenient to offer some way to further deduplicate grouped sets of dependencies that all share the same version.

**Wildcard**

```yaml
# pnpm-workspace.yaml
catalogs:
  react:
    '*': '^18.3.1
```

**Referencing another entry**:

```yaml
# pnpm-workspace.yaml
catalog:
  react: ^18.3.1
  react-dom: catalog:default:react
  react-is: catalog:default:react
```

### Describe the drawbacks of your solution

Both approaches make it harder to automatically upgrade dependencies through `pnpm update`. The `pnpm update` command's implementation would need to understand these grouped sets of dependencies share a version.

I'm not sure whether we should implement this feature yet, but wanted to drop down a feature request describing the problem and gauge whether we should solve it. Please 👍 if you think some solution to this would be valuable.

### Describe alternatives you've considered

N/A

**Comment by zkochan** [comment]
I am not confident this scenario is frequent enough to justify the syntax sugar.

**Comment by gluxon** [comment]
I'm not sure how frequent it is either. We can close this issue if it's not a popular request.

**Comment by alvis** [comment]
With number of mentions of `catalog:` in issue since the release of 9.5, and me using it a lot, I'd say it's a very useful and popular feature! Thanks @gluxon for bringing this feature to life! Well done!

**Comment by martinkors** [comment]
> I don't think you should work on it. How frequent it is that different packages have the same version? It is extremely rare as far as I can tell. This will add additional complexity but only for react and react-dom?

Very true. Will stop working on it 😄

**Comment by beaussan** [comment]
> How frequent it is that different packages have the same version? 

It's a strategy commonly used for groups of packages, like angular, typescript eslint, nx, react, etc. But also very common for design system that publish multiple packages

**Comment by AndreaPontrandolfo** [comment]
Im surprised this didn't got any traction.
In real production codebases this is a real pain-point.
For example in my project, i need this for:
- react and react-dom
- @tanstack/react-query, @tanstack/react-query-devtools and @tanstack/eslint-plugin-query
- @vitest/coverage-v8 and @vitest/ui
- embla-carousel and embla-carousel-react
- Mantine stuff (4-5 deps)
- @react-native-firebase stuff (5-6 deps)
- Expo stuff (7-8 deps)

These are a lot of dependencies sets.
If PNPM could provide a native solution instead of a hacky workaround it would be much better.

**Comment by yacinehmito** [comment]
I second @AndreaPontrandolfo.

@zkochan in our monorepo it's not rare. We have this for:
- Vitest packages
- OpenCode packages
- OpenTelemetry packages
- Tiptap packages
- Effect packages
- ...and I might forget others

**Comment by mbeckem** [comment]
As of #14046 pnpm warn about unknown settings, so the following no longer works without warnings:

```yaml
__versions:
  - &react_version "^18.3.1"

catalog:
    react: *react_version
    react-dom: *react_version
```

Produces:

```text
[WARN] The following settings in pnpm-workspace.yaml are not recognized by this version of pnpm and were ignored: "__versions" (did you mean "version"?).
```

I understand that this is _usually_ what you want to prevent subtle errors due to mistyping an option.
Would it be possible to get a way to hide the warning for specific keys (e.g. via configuration, or a naming convention)?.

**Comment by zkochan** [comment]
YAML anchors are useful for deduplicating catalog specifiers without a new pnpm setting:

```yaml
catalog:
  react: &react_version "^18.3.1"
  react-dom: *react_version
  react-is: *react_version
```

Defining the anchor on a catalog entry also avoids the unknown-setting warning from a custom top-level `__versions` key. I am working on preserving scalar anchors and aliases when pnpm edits the workspace manifest, including when the entry defining an anchor is pruned.

For coordinated updates, we could separately consider allowing catalog entries to reference other catalog entries, as suggested in the issue body:

```yaml
catalog:
  react: ^18.3.1
  react-dom: catalog:default:react
  react-is: catalog:default:react
```

This is a proposal, not syntax pnpm currently supports. An explicit reference would retain the relationship after YAML parsing and give `pnpm update` a way to identify entries that should move together. It would need cycle and missing-target errors, unambiguous handling of scoped package names and existing catalog names, and defined behavior for filtered updates and packages without a common version. That feature is separate from the anchor-preservation fix.

---
Written by an agent (Codex, GPT-6).
