### ISSUE TITLE
Cannot upgrade dependency's dependency with pnpm patch

### ISSUE THREAD

**Issue by Tc-001** [pnpm/pnpm#8397]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.7.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Tc-001/pnpm-patch-bug-repro

### Reproduction steps

- Install a package with an outdated dependency (for this example: `is-even`, it depends on `is-odd ^0.1.2`)
- Verify that it is using the outdated dependency version in `pnpm-lock.yaml`
```yaml
  is-even@1.0.0:
    dependencies:
      is-odd: 0.1.2
```
- `pnpm patch is-even` and change the `package.json` to use a newer version
```diff
-    "is-odd": "^0.1.2"
+    "is-odd": "3.0.1"
```
- `pnpm patch-commit`
- See that the version in the lockfile hasn't changed, and the package is still using `is-odd 0.1.2`
```yaml
  is-even@1.0.0(patch_hash=rjcyzur7cxhvcfpu5dqhrq72iq):
    dependencies:
      is-odd: 0.1.2
```

### Describe the Bug

Patching a dependency's dependency version does not actually upgrade the version as expected.

### Expected Behavior

`is-even`'s `is-odd` should have upgraded to `3.0.1`. That upgrade should have been reflected in the lockfile and package behavior.

### Which Node.js version are you using?

v20.12.2

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Fedora 40
