### ISSUE TITLE
Error with lock file creation

### ISSUE THREAD

**Issue by mbrodala** [pnpm/pnpm#849]
### pnpm version:
1.6.0

### Code to reproduce the issue:
Run `pnpm i` (in `/var/www` here)

Content of pnpm-debug.log file:

```
---
  0 error pnpm:
    message:
      errno: -13
      code: "EACCES"
      syscall: "mkdir"
      path: "/var/www.lock.lock"
    err:
      name: "Error"
      message: "EACCES: permission denied, mkdir '/var/www.lock.lock'"
      code: "EACCES"
      stack: "Error: EACCES: permission denied, mkdir '/var/www.lock.lock'\n    at Error (native)"
```

### Expected behavior:
Packages are installed as usual.

### Actual behavior:
An error occurs:

```
ERROR EACCES: permission denied, mkdir '/var/www.lock.lock'
```

I have to run with `--no-lock` to bypass this.

### Additional information:

 - `node -v` prints: v5.12.0
 - Windows, OS X, or Linux?: Linux
