### ISSUE TITLE
EINTEGRITY error doesn't say for which module

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#872]
```
  27393 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/draft-js/0.10.1"
    pkgVersion: "0.10.1"
  27394 debug pnpm:progress:
    status: "dependencies_installed"
    pkgId: "registry.npmjs.org/draft-js/0.10.1"
  27395 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/fbjs/0.8.14"
    pkgVersion: "0.8.14"
  27396 debug pnpm:progress:
    status: "dependencies_installed"
    pkgId: "registry.npmjs.org/fbjs/0.8.14"
  27397 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/object-assign/4.1.1"
    pkgVersion: "4.1.1"
  27398 debug pnpm:progress:
    status: "dependencies_installed"
    pkgId: "registry.npmjs.org/object-assign/4.1.1"
  27399 debug pnpm:progress:
    status: "dependencies_installed"
    pkgId: "registry.npmjs.org/rc-editor-core/0.7.8"
  27400 debug pnpm:fetch: "finish sha1-E7TTyxK++hVIKib+Gy665kAHHks= https://registry.npmjs.org/immutable/-/immutable-3.7.6.tgz"
  27401 debug pnpm:progress:
    status: "fetched"
    pkgId: "registry.npmjs.org/immutable/3.7.6"
  27402 debug pnpm:progress:
    status: "downloaded_manifest"
    pkgId: "registry.npmjs.org/immutable/3.7.6"
    pkgVersion: "3.7.6"
  27403 debug pnpm:progress:
    status: "dependencies_installed"
    pkgId: "registry.npmjs.org/immutable/3.7.6"
  27404 debug pnpm:progress:
    status: "dependencies_installed"
    pkgId: "registry.npmjs.org/draft-js/0.10.1"
  27405 debug pnpm:progress:
    status: "dependencies_installed"
    pkgId: "registry.npmjs.org/rc-editor-mention/0.6.12"
  27406 debug pnpm:progress:
    status: "dependencies_installed"
    pkgId: "registry.npmjs.org/antd/2.12.5"
  27407 error pnpm:
    message:
      code: "EINTEGRITY"
      found: "sha1-dbSmLq6UB++20xCT5eJrkj11178="
      expected:
        - "sha1-mnHEh0chjrylHlGmbaaCA4zct78="
      algorithm: "sha1"
      sri: "sha1-mnHEh0chjrylHlGmbaaCA4zct78="
    err:
      name: "Error"
      message: "sha1-mnHEh0chjrylHlGmbaaCA4zct78= integrity checksum failed when using sha1: wanted sha1-mnHEh0chjrylHlGmbaaCA4zct78= but got sha1-dbSmLq6UB++20xCT5eJrkj11178=. (4292233 bytes)"
      code: "EINTEGRITY"
      stack: "Error: sha1-mnHEh0chjrylHlGmbaaCA4zct78= integrity checksum failed when using sha1: wanted sha1-mnHEh0chjrylHlGmbaaCA4zct78= but got sha1-dbSmLq6UB++20xCT5eJrkj11178=. (4292233 bytes)\n    at Transform.on (/usr/local/lib/node_modules/pnpm/lib/node_modules/ssri/index.js:275:19)\n    at emitNone (events.js:110:20)\n    at Transform.emit (events.js:207:7)\n    at endReadableNT (_stream_readable.js:1047:12)\n    at _combinedTickCallback (internal/process/next_tick.js:102:11)\n    at process._tickCallback (internal/process/next_tick.js:161:9)"
```

For my particular case it works on macOS but not on Ubuntu.

### Additional information:

 - `node -v` prints: 8.1.2
 - Windows, OS X, or Linux?: Ubuntu 16

BTW: Is there an easier way to check which module it was?
