### ISSUE TITLE
deploy tries to install workspace packages from registry

### ISSUE THREAD

**Issue by also** [pnpm/pnpm#8744]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/also/pnpm-deploy-failure/tree/main

### Reproduction steps

Create three packages in a workspace, all `"version": "1.0.0"`, with dependencies between them such that after `pnpm i` the [lockfile contains](https://github.com/also/pnpm-deploy-failure/blob/0e3dba45d0fee6db21a71c0eb99350aada3c5e1f/pnpm-lock.yaml#L7-L21)

```yml
  packages/a:
    dependencies:
      '@pnpm-deploy-failure/b':
        specifier: workspace:*
        version: link:../b

  packages/b:
    dependencies:
      '@pnpm-deploy-failure/c':
        specifier: 1.0.0
        version: link:../c

  packages/c: {}
```

Run
```
pnpm deploy --filter @pnpm-deploy-failure/a deployed
```

The command fails with
```
ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@pnpm-deploy-failure%2Fc: Not Found - 404

This error happened while installing the dependencies of @pnpm-deploy-failure/b@1.0.0

@pnpm-deploy-failure/c is not in the npm registry, or you have no permission to fetch it.
```

The combination of `workspace:*` and `1.0.0` specifiers seems necessary to trigger the bug. Using the same specifier (either `1.0.0` or `workspace:*`) for both appears to work.

### Describe the Bug

`pnpm deploy` behaves differently from `pnpm install`, failing when a locally-available package is not available in the registry.

### Expected Behavior

`pnpm deploy` should not fail to install dependencies that `pnpm install` is able to install/link in the same workspace.

### Which Node.js version are you using?

20.11.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [X] Linux
