### ISSUE TITLE
Workspaces: Package groups

### ISSUE THREAD

**Issue by ProCode-Software** [pnpm/pnpm#8767]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

I am using pnpm for my [icon library](https://github.com/ProCode-Software/proicons), and I wish there would be an easier way to run a command for multiple packages in different locations, which are all already inside a workspace.

For example, running `pnpm run build` in the root directory (`.`) and all packages inside `./packages` except for `./packages/b`

### Describe the solution you'd like

Since we also have catalog options in the `pnpm-workspace.yaml` file, we could also add a property for groups with group names as keys and glob patterns or package names inside an array as values.

```yaml
packages:
    - 'packages/*'
    - 'tools/*'
    - 'site'
groups:
    myGroup1: ['packages/*', '!packages/excluded-package', '@or-also-a/package-name', '.']
    site: ['site', 'anotherGlob']
```

### Describe alternatives you've considered

Currently, I have to use `pnpm --filter [patterns] run build` to do this
To build `myGroup1` in the example above, I would have to run:
```shell
pnpm --filter ./packages/* --filter !./packages/excluded-package --filter @or-also-a/package/name --filter . run build
```
This can get too much when you run commands on these packages a lot.
(Also, `--filter "."` doesn't even currently work, and I would like to use it to run a command for the root and sub-packages in one command.)
