### ISSUE TITLE
Neither "catalog:" nor "workspace:" protocols are resolved when "pnpm pack" or "pnpm deploy" are used

### ISSUE THREAD

**Issue by emdzej** [pnpm/pnpm#8996]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

9.15.4, 10.0.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/emdzej/pnpm-pack-issue

### Reproduction steps

There is a pnpm workspace set up, described by the `pnpm-workspace.yaml` similar to:

```yaml
packages:
  - packages/*
  - apps/*
catalog:
  "@mui/material": "^5.14.12"
  "@mui/system": "^5.15.12"
  "react": "^18.2.0"
  "react-dom": "^18.2.0"
  "react-router-dom": "^6.16.0"
  "react-scripts": "5.0.1"
```

The `package.json` files throughout the workspace contain dependency definitions similar to:

```json
  "peerDependencies": {
    "@mui/icons-material": "catalog:",
    "@mui/lab": "catalog:",
    "@mui/material": "catalog:",
    "@mui/system": "catalog:",
    "react": "catalog:",
    "react-dom": "catalog:"
}
"dependencies": {
   "@foo/bar": "workspace:*"
}
```

While `pnpm i` works well, the `pack` and `deploy` result in a tarballs with `package.json` files unchanged.

The linked repository contains minimal setup which fails expectations.

### Describe the Bug

The resulting torball contains package.json files with dependencies still containing `catalog:` or `workspace:*` references.

Also - the torball doesn't contain `dist` folders for any of the packages (all package.json files contain `files: ["dist"]`)

### Expected Behavior

Dependency versions are substituted with the correct values from the ppm-workspace.yaml or from workspace.

### Which Node.js version are you using?

21.7.2

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux
