### ISSUE TITLE
Incorrectly links workspace packages causing issues with building the project

### ISSUE THREAD

**Issue by christian-bromann** [pnpm/pnpm#9103]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

10.3.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Link to the code that reproduces this issue or a replay of the bug

n/a

### Reproduction steps

I have a larger project with a lot of workspace packages, it's hard to share or create a reproduction case.

### Describe the Bug

After installing all dependencies via `pnpm install` I see that within the `pnpm-lock.json` the resolved workspace packages (see `@myCompany` scope) don't match:

```yaml
'@myCompany/contracts':
  specifier: workspace:*
  version: link:../../packages/contracts
'@myCompany/data':
  specifier: workspace:*
  version: link:../../packages/data
'@myCompany/detector':
  specifier: workspace:*
  version: file:packages/detector(axios@1.7.9)(cheerio@1.0.0)(encoding@0.1.13)(react@18.3.1)
'@myCompany/instrument':
  specifier: workspace:*
  version: link:../../packages/instrument
'@myCompany/openapi':
  specifier: workspace:*
  version: link:../../packages/openapi
'@myCompany/worker':
  specifier: workspace:*
  version: file:services/worker(axios@1.7.9)(cheerio@1.0.0)(encoding@0.1.13)(openapi3-ts@2.0.2)(react-dom@18.3.1(react@18.3.1))(react@18.3.1)(typescript@5.6.3)
```

The problematic package is `@myCompany/detector` and `@myCompany/worker`. If I look into `@myCompany/openapi` which has a dependency to `@myCompany/detector`, I see it being linked but it doesn't seem to link it to my workspace but treats it as a regular dependency:

```sh
❯ ll ./packages/openapi/node_modules/@myCompany/
   rwxr-xr-x   1   christian.bromann   wheel    153 B     Thu Feb 13 09:16:18 2025    detector  ⇒ ../../../../node_modules/.pnpm/@myCompany+detector@file+packages+detector_axios@1.7.9_cheerio@1.0.0_encoding@0.1.13_react@18.3.1/node_modules/@myCompany/detector
```

Looking into the folder it shows that the package contents were copied:

```sh
❯ ll ./node_modules/.pnpm/@myCompany+detector@file+packages+detector_axios@1.7.9_cheerio@1.0.0_encoding@0.1.13_react@18.3.1/node_modules/@myCompany
   rwxr-xr-x   6   christian.bromann   wheel    192 B     Thu Feb 13 09:16:18 2025    detector/
```

This obviously causes types not being correctly resolved when building all packages.

### Expected Behavior

I would expect that the `@myCompany/detector` correctly links to my workspace rather than to a copy in `node_modules`.

### Which Node.js version are you using?

22

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux
