### ISSUE TITLE
ERR_PNPM_NO_GLOBAL_BIN_DIR with `corepack enable` on GitHub Actions

### ISSUE THREAD

**Issue by karlhorky** [pnpm/pnpm#9191]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/karlhorky/repro-pnpm-global-bin-error-with-github-actions-and-corepack

### Reproduction steps

1. Set up a GitHub Actions workflow using `corepack enable` instead of [`pnpm/action-setup`](https://github.com/pnpm/action-setup)
2. Attempt to use `pnpm add --global` and receive `ERR_PNPM_NO_GLOBAL_BIN_DIR` error
3. Attempt to run `pnpm setup` before this step to set up `$PNPM_HOME`
4. Observe that `$PNPM_HOME` is not set

### Describe the Bug

Using `corepack enable` on GitHub Actions instead of [`pnpm/action-setup`](https://github.com/pnpm/action-setup) leads to a non-working setup for `pnpm add --global`, even if `pnpm setup` is run first

Failing workflow run: https://github.com/karlhorky/repro-pnpm-global-bin-error-with-github-actions-and-corepack/actions/runs/13565764361/job/37918380628

```bash
$ pnpm setup
! Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-10.5.2.tgz
Appended new lines to /home/runner/.bashrc

Next configuration changes were made:
export PNPM_HOME="/home/runner/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

To start using pnpm, run:
source /home/runner/.bashrc
$ pnpm bin --global
$ echo $PNPM_HOME
$ pnpm add --global @upleveled/preflight
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
Error: Process completed with exit code 1.
```

![Image](https://github.com/user-attachments/assets/1eece9fe-003d-44af-aa0a-3606868c7b8d)

### Expected Behavior

Using `corepack enable` on GitHub Actions should allow for easy usage of `pnpm add --global`:

1. Ideally without `pnpm setup`
2. If using `pnpm setup`, it should recognize the shell properly without setting the `SHELL` environment variable
3. If using `pnpm setup`, the environment variable `PNPM_HOME` should persist across steps

### Which Node.js version are you using?

20.18.3

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [x] Linux

**Comment by karlhorky** [comment]
## Workaround

Set `PNPM_HOME` manually in a GitHub Actions workflow step and add to `PATH`, eg. for Windows and Linux:

```yml
      - run: corepack enable

      # Set up PNPM_HOME directory to avoid errors such
      # as `ERR_PNPM_NO_GLOBAL_BIN_DIR`:
      #
      # ```
      #  ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory
      # Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
      # ```
      #
      # - https://github.com/pnpm/pnpm/issues/9191#issuecomment-2687756396
      - name: Set up pnpm global bin directory for `pnpm add --global`
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            PNPM_HOME=/c/Program\ Files/Git/home/runner/.local/share/pnpm
          elif [ "$RUNNER_OS" == "Linux" ]; then
            PNPM_HOME=/home/runner/.local/share/pnpm
          fi
          echo "PNPM_HOME=$PNPM_HOME" >> "$GITHUB_ENV"
          echo "$PNPM_HOME" >> "$GITHUB_PATH"
```

---

Update: after pnpm v11, this requires adding `$PNPM_HOME/bin` to `$GITHUB_PATH`, as per [the pnpm v11 release notes](https://pnpm.io/blog/releases/11.0#:~:text=Globally%20installed%20binaries%20now%20live%20in%20a%20bin%20subdirectory%20of%20PNPM_HOME%20(rather%20than%20directly%20in%20PNPM_HOME)):

> "Globally installed binaries are now stored in a `bin` subdirectory of `PNPM_HOME` instead of directly in `PNPM_HOME`."

```yml
      - run: corepack enable

      # Set up PNPM_HOME directory to avoid errors such
      # as `ERR_PNPM_NO_GLOBAL_BIN_DIR`:
      #
      # ```
      #  ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory
      # Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
      # ```
      #
      # - https://github.com/pnpm/pnpm/issues/9191#issuecomment-2687756396
      - name: Set up pnpm global bin directory for `pnpm add --global`
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            PNPM_HOME=/c/Program\ Files/Git/home/runner/.local/share/pnpm
          elif [ "$RUNNER_OS" == "Linux" ]; then
            PNPM_HOME=/home/runner/.local/share/pnpm
          fi
          echo "PNPM_HOME=$PNPM_HOME" >> "$GITHUB_ENV"
          echo "$PNPM_HOME/bin" >> "$GITHUB_PATH"
```
