### ISSUE TITLE
pnpm 10.6.0 breaks patchedDependencies

### ISSUE THREAD

**Issue by th3fallen** [pnpm/pnpm#9226]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

10.6.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

Package manager compatibility

### Reproduction steps

have an existing project with any patched dependency on 10.5.2, then update pnpm to 10.6.0 and run `pnpm install` the result will be a change to your lock file removing all references to the patchedDependencies.

![Image](https://github.com/user-attachments/assets/293e5660-5f52-47ea-aa24-28db09be9772)

### Describe the Bug

PatchedDependencies are not applied in 10.6.0

### Expected Behavior

patchedDependencies should be applied in 10.6.0

### Which Node.js version are you using?

v22.14.0

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [x] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

debian

**Comment by ntnyq** [comment]
Workaround, move `patchedDependencies` from `package.json` to `pnpm-workspace.yaml`:

```yaml
# pnpm-workspace.yaml

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
patchedDependencies:
  tsup: patches/tsup.patch
```
