### ISSUE TITLE
Updating an individual package can result in broken peer dependencies

### ISSUE THREAD

**Issue by gzm0** [pnpm/pnpm#9352]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Reproduction steps

In an empty directory, run

```sh
$ npx pnpm@10.7.0 install @mui/icons-material@6 --lockfile-only
$ npx pnpm@10.7.0 install @mui/icons-material@7 --lockfile-only
```

### Describe the Bug

In the resulting lockfile, `@mui/icons-material` has `@mui/material@6` as peer dependency:

```yaml
      '@mui/icons-material':
        specifier: ^7.0.1
        version: 7.0.1(@mui/material@6.4.9(@types/react@19.0.12)(react-dom@19.1.0(react@19.1.0))(react@19.1.0))(@types/react@19.0.12)(react@19.1.0)
```

However, the package requires `^7.0.1`:

```yaml
  '@mui/icons-material@7.0.1':
    resolution: {integrity: sha512-x8Em7LISFQ6s/KeZj6ZKwJHq2WttRNe9KJLWFa72eQx7B53s/TzMKOEjGKB/YyhOx+bqqSv1pMvK373M4Xf07A==}
    engines: {node: '>=14.0.0'}
    peerDependencies:
      '@mui/material': ^7.0.1
      '@types/react': ^17.0.0 || ^18.0.0 || ^19.0.0
      react: ^17.0.0 || ^18.0.0 || ^19.0.0
    peerDependenciesMeta:
      '@types/react':
        optional: true
```

### Expected Behavior

Expected resolution:

```yaml
      '@mui/icons-material':
        specifier: ^7.0.1
        version: version: 7.0.1(@mui/material@7.0.1(@types/react@19.0.12)(react-dom@19.1.0(react@19.1.0))(react@19.1.0))(@types/react@19.0.12)(react@19.1.0)
```

Note that this is the result of a clean install (which is also a workaround for this issue):

```
$ npx pnpm@10.7.0 remove @mui/icons-material --lockfile-only
$ npx pnpm@10.7.0 install @mui/icons-material@7 --lockfile-only
```

### Which Node.js version are you using?

v22.11.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [x] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu 24.04.1 LTS
