### ISSUE TITLE
Support version constraints and multiple file paths for `onlyBuiltDependencies`

### ISSUE THREAD

**Issue by sj817** [pnpm/pnpm#9471]
### Contribution

- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

## Background

The `onlyBuiltDependencies` field restricts which dependencies run their lifecycle scripts, and `onlyBuiltDependenciesFile` points to an external JSON allow list. The `pnpm approve-builds` command reviews blocked builds and lets you approve them.

## Proposal

1. **Version constraints in `onlyBuiltDependencies`**  
   Accept semver ranges alongside package names. Example:  
   ```yaml
   onlyBuiltDependencies:
     - '@heroui/shared-utils'
     - 'esbuild<=1.0.0'
     - '@swc/core>=1.2.0 <2.0.0'
   ```  
   This lets teams pin builds to known-safe versions and avoid pulling in unwanted updates.

2. **Multiple `onlyBuiltDependenciesFile` paths**  
   Allow an array of file paths or URLs:  
   ```yaml
   onlyBuiltDependenciesFile:
     - node_modules/.pnpm-config/@my-org/policy/onlyBuiltDependencies.json
     - onlyBuiltDependenciesFile.json
     - https://raw.githubusercontent.com/xxx/xxx/main/onlyBuiltDependencies.json
   ```  
   When the same package appears in several files, entries in later files override earlier ones. This lets orgs overlay their own rules on top of community policies.

## Example Configuration

```yaml
packages:
  - 'packages/*'

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - 'esbuild<=1.0.0'
  - '@swc/core>=1.2.0 <2.0.0'

onlyBuiltDependenciesFile:
  - node_modules/.pnpm-config/@my-org/policy/onlyBuiltDependencies.json
  - onlyBuiltDependenciesFile.json
  - https://cdn.jsdelivr.net/gh/pnpm-community/policies@main/onlyBuiltDependencies.json
```

## Benefits

- **Security**: Limits builds to vetted versions, reducing supply-chain risk.  
- **Flexibility**: Layer community and org-specific allowlists.  
- **Backward compatibility**: Unversioned entries work as before.

---

Thank you!

### Describe the solution you'd like

- `onlyBuiltDependencies` supports version constraints
- Multiple `onlyBuiltDependenciesFile` paths

**Comment by zkochan** [comment]
Regarding allowing only a subset of versions to be built, we could support this but I am not sure how useful it would be. The majority of users will probably just blindly trust all versions if they allowed a package once. But some companies might have stricter policies. 

Loading multiple files is probably OK. But I don't think we will support loading from URL. If that is needed, then just use a [config dependency](https://pnpm.io/config-dependencies#updating-pnpm-settings-dynamically).

But I am also thinking about maybe sharing [ignoredBuiltDependencies](https://pnpm.io/settings#ignoredbuiltdependencies).

Maybe we should do something like a new format:

```yaml
allowBuild:
  esbuild@1.0.0: true
  '@swc/core>=1.2.0 <2.0.0': true
  'core-js': false
```
