### ISSUE TITLE
Wrong peer dependency being resolved

### ISSUE THREAD

**Issue by jzhan-canva** [pnpm/pnpm#9599]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

v10.11.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Reproduction steps

Say I have a package.json
```json
{
  "name": "wrongPeer",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react18": "npm:react@18.3.1",
    "react19": "npm:react@19.0.0",
    "react-dom18": "npm:react-dom@18.3.1",
    "react-dom19": "npm:react-dom@19.0.0"
  }
}
```

react-dom@18.3.1 has peer dependency `"react": "^18.3.1"`
react-dom@19.0.0 has peer dependency `"react": "^19.0.0"`

### Describe the Bug

however, when I install, I got

<img width="445" alt="Image" src="https://github.com/user-attachments/assets/620bd29d-5b82-470a-b7c2-9e5e21b0fa49" />

and in `pnpm-lock.yaml` snapshots, I got
```yaml
  react-dom@18.3.1(react@19.0.0):
    dependencies:
      loose-envify: 1.4.0
      react: 19.0.0
      scheduler: 0.23.2

  react-dom@19.0.0(react@19.0.0):
    dependencies:
      react: 19.0.0
      scheduler: 0.25.0

  react@18.3.1:
    dependencies:
      loose-envify: 1.4.0

  react@19.0.0: {}
```

that `react-dom@18.3.1` incorrectly depends on `react@19.0.0`

### Expected Behavior

react-dom should depend on correct peer dependency
```yaml
  react-dom@18.3.1(react@18.3.1):
    dependencies:
      loose-envify: 1.4.0
      react: 18.3.1
      scheduler: 0.23.2

  react-dom@19.0.0(react@19.0.0):
    dependencies:
      react: 19.0.0
      scheduler: 0.25.0

  react@18.3.1:
    dependencies:
      loose-envify: 1.4.0

  react@19.0.0: {}
```

### Which Node.js version are you using?

v20.18.1

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux
