### ISSUE TITLE
False Positive: ` WARN  Skip adding ${packageName} to the default catalog because it already exists as ${version}. Please use `pnpm update` to update the catalogs.`

### ISSUE THREAD

**Issue by bestickley** [pnpm/pnpm#9662]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

v10.12.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

See logs below

### Reproduction steps

```
pnpm i
Scope: all 7 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
. prepare$ husky
└─ Done in 240ms
Done in 771ms using pnpm v10.12.1
pnpm i
Scope: all 8 workspace projects
 WARN  Skip adding @eslint/eslintrc to the default catalog because it already exists as ^3.3.1. Please use `pnpm update` to update the catalogs.
 WARN  Skip adding @eslint/js to the default catalog because it already exists as ^9.29.0. Please use `pnpm update` to update the catalogs.
 WARN  Skip adding @types/node to the default catalog because it already exists as ^22.15.32. Please use `pnpm update` to update the catalogs.
 WARN  Skip adding aws-cdk to the default catalog because it already exists as ^2.1018.1. Please use `pnpm update` to update the catalogs.
 WARN  Skip adding eslint to the default catalog because it already exists as ^9.29.0. Please use `pnpm update` to update the catalogs.
 WARN  49 other warnings
Packages: +51
+++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 607, reused 490, downloaded 5, added 51, done
. prepare$ husky
└─ Done in 345ms
Done in 2.7s using pnpm v10.12.1
pnpm update
 WARN  `node_modules` is present. Lockfile only installation will make it out-of-date
 WARN  Skip adding @types/react to the default catalog because it already exists as ^19.1.0. Please use `pnpm update` to update the catalogs.
 WARN  Skip adding @types/react-dom to the default catalog because it already exists as ^19.1.0. Please use `pnpm update` to update the catalogs.
 WARN  Skip adding @tailwindcss/postcss to the default catalog because it already exists as ^4.1.10. Please use `pnpm update` to update the catalogs.
 WARN  Skip adding next to the default catalog because it already exists as ^15.3.3. Please use `pnpm update` to update the catalogs.
 WARN  33 other warnings
Progress: resolved 607, reused 0, downloaded 0, added 0, done
Already up to date
. prepare$ husky
└─ Done in 227ms
Done in 3.4s using pnpm v10.12.1
pnpm i
Scope: all 8 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
. prepare$ husky
└─ Done in 182ms
Done in 716ms using pnpm v10.12.1
pnpm i --force
 WARN  using --force I sure hope you know what you are doing
Scope: all 8 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +607
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading turbo-darwin-64@2.5.4: 13.68 MB/13.68 MB, done
Downloading turbo-linux-64@2.5.4: 14.29 MB/14.29 MB, done
Downloading turbo-linux-arm64@2.5.4: 13.88 MB/13.88 MB, done
Downloading @img/sharp-libvips-linux-arm@1.1.0: 6.56 MB/6.56 MB, done
Downloading turbo-windows-arm64@2.5.4: 15.04 MB/15.04 MB, done
Downloading @img/sharp-libvips-linux-x64@1.1.0: 7.40 MB/7.40 MB, done
Downloading @img/sharp-libvips-darwin-x64@1.1.0: 8.17 MB/8.17 MB, done
Downloading @img/sharp-libvips-linux-ppc64@1.1.0: 7.63 MB/7.63 MB, done
Downloading @img/sharp-libvips-linuxmusl-x64@1.1.0: 7.53 MB/7.53 MB, done
Downloading @img/sharp-libvips-linux-arm64@1.1.0: 7.62 MB/7.62 MB, done
Downloading @img/sharp-win32-arm64@0.34.2: 7.54 MB/7.54 MB, done
Downloading @img/sharp-libvips-linux-s390x@1.1.0: 6.71 MB/6.71 MB, done
Downloading @img/sharp-win32-ia32@0.34.2: 8.37 MB/8.37 MB, done
Downloading @img/sharp-libvips-linuxmusl-arm64@1.1.0: 7.63 MB/7.63 MB, done
Downloading @img/sharp-win32-x64@0.34.2: 8.45 MB/8.45 MB, done
Downloading turbo-windows-64@2.5.4: 15.04 MB/15.04 MB, done
Downloading @next/swc-linux-x64-musl@15.3.3: 48.09 MB/48.09 MB, done
Downloading @next/swc-win32-arm64-msvc@15.3.3: 38.34 MB/38.34 MB, done
Downloading @next/swc-darwin-x64@15.3.3: 43.83 MB/43.83 MB, done
Downloading @next/swc-linux-arm64-gnu@15.3.3: 44.13 MB/44.13 MB, done
Downloading @next/swc-linux-arm64-musl@15.3.3: 43.45 MB/43.45 MB, done
Downloading @next/swc-linux-x64-gnu@15.3.3: 48.12 MB/48.12 MB, done
Downloading @next/swc-win32-x64-msvc@15.3.3: 47.33 MB/47.33 MB, done
Progress: resolved 607, reused 519, downloaded 88, added 607, done
node_modules/.pnpm/@tailwindcss+oxide@4.1.10/node_modules/@tailwindcss/oxide: Running postinstall script, done in 172ms
node_modules/.pnpm/sharp@0.34.2/node_modules/sharp: Running install script, done in 1.9s
. prepare$ husky
└─ Done in 338ms
Done in 18.4s using pnpm v10.12.1
pnpm i
Scope: all 8 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
. prepare$ husky
└─ Done in 206ms
Done in 733ms using pnpm v10.12.1
pnpm update
 WARN  `node_modules` is present. Lockfile only installation will make it out-of-date
 WARN  Skip adding @types/react to the default catalog because it already exists as ^19.1.0. Please use `pnpm update` to update the catalogs.
 WARN  Skip adding @types/react-dom to the default catalog because it already exists as ^19.1.0. Please use `pnpm update` to update the catalogs.
 WARN  Skip adding @tailwindcss/postcss to the default catalog because it already exists as ^4.1.10. Please use `pnpm update` to update the catalogs.
 WARN  Skip adding next to the default catalog because it already exists as ^15.3.3. Please use `pnpm update` to update the catalogs.
 WARN  33 other warnings
Progress: resolved 607, reused 0, downloaded 0, added 0, done
Already up to date
. prepare$ husky
└─ Done in 236ms
Done in 3s using pnpm v10.12.1
```

```
packages:
  - apps/data/*
  - packages/shared/*
  - '!**/cdk.out/**'
  - '!**/.next/**'

catalog:
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.29.0
  '@tailwindcss/postcss': ^4.1.10
  '@ts-rest/core': ^3.53.0-rc.1
  '@ts-rest/fastify': ^3.53.0-rc.1
  '@ts-rest/open-api': ^3.53.0-rc.1
  '@tsconfig/next': ^2.0.3
  '@tsconfig/node22': ^22.0.1
  '@tsconfig/strictest': ^2.0.5
  '@types/aws-lambda': ^8.10.149
  '@types/node': ^22.15.32
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.0
  aws-cdk: ^2.1018.1
  aws-cdk-lib: ^2.201.0
  cdk-monitoring-constructs: ^9.10.0
  cdk-nag: ^2.35.98
  cdk-nextjs: ^0.4.2
  constructs: ^10.4.2
  dotenv-cli: ^8.0.0
  drizzle-kit: ^0.31.1
  drizzle-orm: ^0.43.1
  electrodb: ^3.4.1
  esbuild: ^0.25.5
  eslint: ^9.29.0
  eslint-config-next: ^15.3.3
  eslint-config-turbo: ^2.5.4
  globals: ^16.2.0
  husky: ^9.1.7
  next: ^15.3.3
  next-auth: ^5.0.0-beta.28
  lint-staged: ^16.1.2
  postcss: ^8.5.6
  prettier: ^3.5.3
  react: ^19.1.0
  react-dom: ^19.1.0
  server-only: ^0.0.1
  tailwindcss: ^4.1.10
  tsx: ^4.20.3
  turbo: ^2.5.4
  typescript: ^5.8.3
  typescript-eslint: ^8.34.1
  vitest: ^3.2.4
  zod: ^3.25.65

catalogMode: strict

disallowWorkspaceCycles: true

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver

```

### Describe the Bug

I keep getting the false positive error message: ` WARN  Skip adding ${packageName} to the default catalog because it already exists as ${version}. Please use `pnpm update` to update the catalogs.` but I don't think I should be. Error message seems to indicate that I already have `@eslint/eslintrc`, `@eslint/js`, ... installed but see pnpm-workspace.yaml, I do not have duplicates. Maybe I have duplicates in transitive dependencies? Here is code that produces warning in pnpm:

https://github.com/pnpm/pnpm/blob/a050b5090a4582bc6b13389d4206d8087d0cd04e/pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts#L245

### Expected Behavior

No warning.

### Which Node.js version are you using?

22.14.0

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux
