### ISSUE TITLE
pnpm does not respect the `savePrefix` option

### ISSUE THREAD

**Issue by yeskunall** [pnpm/pnpm#9681]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### Reproduction steps

- Create `pnpm-workspace.yaml` with `savePrefix` set to `''`
- Install a dependency (in my case, I used `pnpm add -D`)
- `package.json` modified with the updated dependencies saved with the default prefix (`^`)

### Describe the Bug

pnpm does not respect the `savePrefix` defined in `pnpm-workspace.yaml`. Here’s mine for a Next.js project (no monorepo setup):

```yml
onlyBuiltDependencies:
  - '@tailwindcss/oxide'

savePrefix: ''

supportedArchitectures:
  os: [current]
  cpu: [x64]
```

Here’s my `pnpm-lock.yaml` after the installation succeeds:

```yml
'@types/react':
  specifier: ^19.1.8
  version: 19.1.8
```

### Expected Behavior

It should save/update packages without a prefix, as documented [here](https://pnpm.io/settings#saveprefix).

### Which Node.js version are you using?

v22.16.0

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux
