### ISSUE TITLE
`pnpm patch` not working with git urls

### ISSUE THREAD

**Issue by STofone** [pnpm/pnpm#9699]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

10.12.4

### Reproduction steps

1. install
```shell
pnpm install git://github.com/DetachHead/basedpyright.git#v1.29.4
```
install successfully
package.json
```json
  "dependencies": {
...
    "pyright-root": "github:DetachHead/basedpyright#v1.29.4",
...
  }
```
pnpm-lock.yaml
```yaml
importers:

  .:
    dependencies:
      pyright-root:
        specifier: github:DetachHead/basedpyright#v1.29.4
        version: https://codeload.github.com/DetachHead/basedpyright/tar.gz/46498cf78c1421ef0cc42102c2faf9852c0172f8
packages:
  pyright-root@https://codeload.github.com/DetachHead/basedpyright/tar.gz/46498cf78c1421ef0cc42102c2faf9852c0172f8:
    resolution: {tarball: https://codeload.github.com/DetachHead/basedpyright/tar.gz/46498cf78c1421ef0cc42102c2faf9852c0172f8}
    version: 0.0.0
```
2. create patch
```shell
pnpm patch pyright-root
```
output
```shell
pnpm patch pyright-root                                          
Patch: You can now edit the package at:

  E:\ProgSpace\vast-py-testlib\.vscode\extensions\vast-testlib-ls\node_modules\.pnpm_patches\pyright-root@https+codeload.github.com+DetachHead+basedpyright+tar.gz+46498cf78c1421ef0cc42102c2faf9852c0172f8

To commit your changes, run:

  pnpm patch-commit "E:\ProgSpace\vast-py-testlib\.vscode\extensions\vast-testlib-ls\node_modules\.pnpm_patches\pyright-root@https+codeload.github.com+DetachHead+basedpyright+tar.gz+46498cf78c1421ef0cc42102c2faf9852c0172f8"
```
3. patch-commit
```shell
pnpm patch-commit "E:\ProgSpace\vast-py-testlib\.vscode\extensions\vast-testlib-ls\node_modules\.pnpm_patches\pyright-root@https+codeload.github.com+DetachHead+basedpyright+tar.gz+46498cf78c1421ef0cc42102c2faf9852c0172f8"
```
output
```shell
 ERR_PNPM_FETCH_404  GET https://mirrors.tools.huawei.com/npm/pyright-root: Not Found - 404

pyright-root is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.
```
4. manual set `applyToAll` to false
```json
{
  "E:\\ProgSpace\\vast-py-testlib\\.vscode\\extensions\\vast-testlib-ls\\node_modules\\.pnpm_patches\\pyright-root@https+codeload.github.com+DetachHead+basedpyright+tar.gz+46498cf78c1421ef0cc42102c2faf9852c0172f8": {
    "patchedPkg": "pyright-root",
    "applyToAll": false
  }
}
```
`patch commit`, but still the same error

### Describe the Bug

patch-commit not working

### Expected Behavior

fetch from git url not registry
### Which Node.js version are you using?

22.13.0

### Which operating systems have you used?

- [ ] macOS
- [x] Windows
- [ ] Linux
